---
title: "Maxent Summary for Wyong report"
author: "Amy Whitehead"
date: "Monday, December 08, 2014"
output: html_document
---


```{r}
rm(list=ls())

library(dplyr)

# computer <- "~" #My computer
#computer <- "Z:/Amy" #Super computer
computer <- "//654cw-20990/Amy"

source("C:/Users/awhitehead/Dropbox/Random R code/rbind.columns.r")

# define paths for input and output files
maxent.dir <- paste0(computer,'/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/')

taxa <- c("birds","mammals","plants","reptiles","amphibians")

protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))

wyong.sp <- read.table(paste0(computer,"/GIS_data/Hunter/zonation/wyong/wyong.zonation.w2.spp"),sep="\t")
  wyong.sp <- wyong.sp[grepl("SDM",wyong.sp[,6]),6]
  wyong.sp <- gsub("_"," ",gsub("_SDM_wyong.tif","",wyong.sp))

```


```{r extract maxent results}
envi.parameters <- c("Taxa","Family","Species","Status","MNES","N.records","Training.samples","N.trees","Test.AUC","AUC.Standard.Deviation","cold_temp","hot_temp","mean_rain","seasonal_rain","mean_solar","slope","rugg1000","terr1000","wetness","final_vegetation","2000Dry_sclerophyll_forests","2000Forested_Wetlands","2000Freshwater_Wetlands","2000Grasslands","2000Grassy_Woodlands","2000Heathlands","2000Rainforests","2000Saline_Wetlands","2000Wet_sclerophyll_forests","fert","soil","wii")

for (i in seq(taxa)){
  maxentResults <- read.csv(paste0(maxent.dir,taxa[i],"/pre1750/MaxentResults.csv"))
    maxentResults <- maxentResults[grepl("average",maxentResults$Species),]
  parameters <- c("Species","X.Training.samples","Test.AUC","AUC.Standard.Deviation",names(maxentResults[grepl("permutation.importance",names(maxentResults))]))
  
  maxentResults <- maxentResults[,names(maxentResults) %in% as.character(parameters)]
  
  names(maxentResults) <- gsub("X\\.|X|.permutation.importance","",names(maxentResults))

  maxentResults$Species <- gsub("_"," ",gsub(" \\(average\\)","",maxentResults$Species))

  maxentResults <- maxentResults[maxentResults$Species %in% as.character(wyong.sp),]
  maxentResults <- maxentResults[order(maxentResults$Species),]
# maxentResults[,5:ncol(maxentResults)] <- round(maxentResults[,5:ncol(maxentResults)],2)
#  maxentResults$Test.AUC <- paste0(round(maxentResults$Test.AUC,3)," (",round(maxentResults$AUC.Standard.Deviation,3),")")
# maxentResults <- maxentResults[,!names(maxentResults) %in% "AUC.Standard.Deviation"]
  maxentResults$Taxa <- taxa[i]
  maxentResults$Family <- protected.species$Family[protected.species$Scientific.Name %in% maxentResults$Species]
  maxentResults$Status <- protected.species$combined.status[protected.species$Scientific.Name %in% maxentResults$Species]
  maxentResults$MNES <- protected.species$mnes[protected.species$Scientific.Name %in% maxentResults$Species]
  maxentResults$N.records <- protected.species$greater.hunter[protected.species$Scientific.Name %in% maxentResults$Species]
  envi.order <- envi.parameters[envi.parameters %in% names(maxentResults)]  
  maxentResults <- maxentResults[,envi.order]

assign(paste0(taxa[i],"_MR"),maxentResults)
 write.csv(maxentResults,paste0(maxent.dir,taxa[i],"_wyong report - maxent summary.csv"),row.names=F) 
}

```


```{r tecs}
  maxentResults <- read.csv(paste0(maxent.dir,"/tecs/BRT/contributions.csv"))
   parameters <- c("tec","n.records","cv.roc.mean","cv.roc.se",names(maxentResults[grepl("permutation.importance",names(maxentResults))]))
  
  maxentResults <- maxentResults[,!names(maxentResults) %in% c("lr","cv.correlation.mean","cv.correlation.se","cv.deviance.mean","cv.deviance.se")]
  
  names(maxentResults) <- gsub("X","",names(maxentResults))
  names(maxentResults)[names(maxentResults) %in% c("tec","ntrees","cv.roc.mean","cv.roc.se","n.records")] <- c("Species","N.trees","Test.AUC","AUC.Standard.Deviation","N.records")
  maxentResults$Species <- gsub("_"," ",maxentResults$Species)
  maxentResults <- maxentResults[maxentResults$Species %in% as.character(wyong.sp),]
  maxentResults <- maxentResults[order(maxentResults$Species),]
# maxentResults[,!names(maxentResults) %in% c("Species","N.trees","Test.AUC","AUC.Standard.Deviation","N.records")] <- round(maxentResults[,!names(maxentResults) %in% c("Species","N.trees","Test.AUC","AUC.Standard.Deviation","N.records")],2)
#  maxentResults$Test.AUC <- paste0(round(maxentResults$Test.AUC,3)," (",round(maxentResults$AUC.Standard.Deviation,3),")")
# maxentResults <- maxentResults[,!names(maxentResults) %in% "AUC.Standard.Deviation"]
maxentResults$Taxa <- "EEC"
maxentResults$Family <- ""

envi.order <- envi.parameters[envi.parameters %in% names(maxentResults)]  
maxentResults <- maxentResults[,envi.order]

assign(paste0("EEC_MR"),maxentResults)
 write.csv(maxentResults,paste0(maxent.dir,"EEC_wyong report - maxent summary.csv"),row.names=F)  

```

```{r combine outputs}
output <- rbind.columns(birds_MR,mammals_MR)
  output <- rbind.columns(output,plants_MR)
  output <- rbind.columns(output,reptiles_MR)
  output <- rbind.columns(output,amphibians_MR)
  output <- rbind.columns(output,EEC_MR)

output <- output[order(output$Species),]
envi.order <- envi.parameters[envi.parameters %in% names(output)] 
output <- output[,envi.order]

write.csv(output,paste0(maxent.dir,"wyong report - maxent summary.csv"),row.names=F)

poorly.modelled <- output[output$Test.AUC<0.7,c("Taxa","Species","Status","MNES","N.records","Test.AUC")]
write.csv(poorly.modelled,paste0(maxent.dir,"wyong report - poorly modelled species.csv"),row.names=F)
```

```{r mean summary table}
names(output) <- gsub("2000","",names(output))

summary <- {
  output %>%
    group_by(Taxa) %>%
      summarise(
        N = n(),
        AUC.mean = mean(Test.AUC, na.rm=T),
        AUC.se = se(Test.AUC),
        cold_temp.mean = mean(cold_temp, na.rm=T),
        cold_temp.se = se(cold_temp),
        hot_temp.mean = mean(hot_temp, na.rm=T),
        hot_temp.se = se(hot_temp),
        mean_rain.mean = mean(mean_rain, na.rm=T),
        mean_rain.se = se(mean_rain),
        seasonal_rain.mean = mean(seasonal_rain, na.rm=T),
        seasonal_rain.se = se(seasonal_rain),
        mean_solar.mean = mean(mean_solar),
        mean_solar.se = se(mean_solar),
        slope.mean = mean(slope, na.rm=T),
        slope.se = se(slope),
        rugg1000.mean = mean(rugg1000, na.rm=T),
        rugg1000.se = se(rugg1000),
        terr1000.mean = mean(terr1000, na.rm=T),
        terr1000.se = se(terr1000),
        wetness.mean = mean(wetness, na.rm=T),
        wetness.se = se(wetness),
        final_vegetation.mean = mean(final_vegetation, na.rm=T),
        final_vegetation.se = se(final_vegetation),
        Dry_sclerophyll_forests.mean = mean(Dry_sclerophyll_forests, na.rm=T),
        Dry_sclerophyll_forests.se = se(Dry_sclerophyll_forests),
        Forested_Wetlands.mean = mean(Forested_Wetlands, na.rm=T),
        Forested_Wetlands.se = se(Forested_Wetlands),
        Freshwater_Wetlands.mean = mean(Freshwater_Wetlands, na.rm=T),
        Freshwater_Wetlands.se = se(Freshwater_Wetlands),
        Grasslands.mean = mean(Grasslands, na.rm=T),
        Grasslands.se = se(Grasslands),
        Grassy_Woodlands.mean = mean(Grassy_Woodlands, na.rm=T),
        Grassy_Woodlands.se = se(Grassy_Woodlands),
        Heathlands.mean = mean(Heathlands, na.rm=T),
        Heathlands.se = se(Heathlands),
        Rainforests.mean = mean(Rainforests, na.rm=T),
        Rainforests.se = se(Rainforests),
        Saline_Wetlands.mean = mean(Saline_Wetlands, na.rm=T),
        Saline_Wetlands.se = se(Saline_Wetlands),
        Wet_sclerophyll_forests.mean = mean(Wet_sclerophyll_forests, na.rm=T),
        Wet_sclerophyll_forests.se = se(Wet_sclerophyll_forests),
        fert.mean = mean(fert, na.rm=T),
        fert.se = se(fert),
        soil.mean = mean(soil, na.rm=T),
        soil.se = se(soil),
        wii.mean = mean(wii, na.rm=T),
        wii.se = se(wii)        
        )
}

summary.table <- as.data.frame(summary)
  summary.table <- as.data.frame(t(summary.table[,2:ncol(summary.table)]))
  names(summary.table) <- c("EEC","amphibians","birds","mammals","plants","reptiles")
  summary.table <- round(summary.table,2)

write.csv(summary.table,paste0(maxent.dir,"wyong report - maxent parameter summary.csv"),row.names=T)




```

```{r plot uncertainties}
library(fields)
library(maptools)

GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

GH.shp <- shapefile("~/GIS_data/Hunter/All data from harddrive/From HCCREMS/Boundaries/AoI/HCCREMS_LGA.shp")
  wyong.shp <- GH.shp[grepl("WYONG",GH.shp$lganame),]
    wyong.shp <- spTransform(wyong.shp,GDA94.56)

uncertainty <- raster(paste0(maxent.dir,"median.uncertainty.tif"))
range.cv <- cellStats(uncertainty,range)

png(paste0(maxent.dir,"wyong_median uncertainties.png"),width=15,height=15,units="cm",res=300,pointsize=12,bg="transparent")
  par(mfrow=c(1,1),mar=c(0,0,0,0),oma=c(0,0,0,0))
  
  plot(uncertainty,axes=F,box=F,legend=F,col=rev(grey((1:90)/100)),zlim=c(range.cv[1],range.cv[2]))
    image.plot(legend.only=TRUE,zlim=range.cv, nlevel=100, col=rev(grey((1:90)/100)),axis.args=list(at=range.cv, labels=c(paste0("Low","\n","(CV=",round(range.cv[1],2),")"),paste0("High","\n","(CV=",round(range.cv[2],2),")")), cex.axis=0.7,adj=0.5),legend.args=list(text='Uncertainty', side=3, font=2, line=1.5, cex=0.7),legend.width=0.55,legend.shrink=0.5,small.plot=c(0.8,0.9,0.1,5))
    plot(wyong.shp, add=T)
dev.off()


```


```{r plot AUC values}

output$Taxa <- factor(output$Taxa, levels=c("amphibians","birds","mammals","plants","reptiles","EEC"))

png(paste0(maxent.dir,"wyong_AUC_boxplot.png"),width=15,height=15,units = "cm",pointsize=12,bg="transparent",res=300)
par(las=1,mar=c(4,6,2,3))
boxplot(Test.AUC~Taxa, data=output, xlab="AUC",horizontal = T)
abline(v=0.7,lty=3)
axis(side=4,at=c(1:6),labels=rev(c(nrow(EEC_MR),nrow(reptiles_MR),nrow(plants_MR),nrow(mammals_MR),nrow(birds_MR),nrow(amphibians_MR))),tick = F)
dev.off()


```
