---
title: "Plots for Wyong report"
author: "Amy Whitehead"
date: "Thursday, November 13, 2014"
output: html_document
---

```{r setup}
rm(list=ls())
library(raster)
library(rgdal)
library(maptools)
library(colorRamps)
library(RColorBrewer)
library(rgeos)
library(fields)
library(scales)


source("C:/Users/awhitehead/Dropbox/Random R code/shp2raster.r")

# define input path
# super computer
input.path <- ('//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Output/')
setwd("//654cw-20990/Amy/GIS_data/Wyong/")
# laptop
# input.path <- ('C:/Users/hkujala/work/RSPs/Wyong/Zonation')

# define top fractions of interest
top.fraction <- c(0.05, 0.1, 0.15, 0.3)

# plotting
pri.col = c('dark grey', 'turquoise', 'yellow', 'orange', 'red')
pa.col = c('palegreen3', 'palegreen4')
map.background <- 'light grey'

leg.labels <- c("top 5%","top 10%","top 15%","top 30%","rest")

GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

# Create maps of priority sites
# NB that this code splits the rank layer to two (unprotected areas & protected areas)

# background map
bg <- raster('//654cw-20990/Amy/GIS_data/Hunter/mask files/wyong.lakes.mask.tif')
veg.mask <- raster('//654cw-20990/Amy/GIS_data/Hunter/mask files/wyong.clipping.mask.tif')

veg.mask.0 <- veg.mask
  veg.mask.0[is.na(veg.mask.0)] <- 0
  veg.mask.0[veg.mask.0==1] <- 0.5
  veg.mask.0 <- mask(veg.mask.0,bg)


GH.shp <- readShapePoly("//654cw-20990/Amy/GIS_data/Hunter/GIS data from various sources/All data from harddrive/From HCCREMS/Boundaries/AoI/HCCREMS_LGA.shp",proj4=GDA94)
  GH.shp <- spTransform(GH.shp,GDA94.56)
  wyong.shp <- GH.shp[grepl("WYONG",GH.shp$lganame),]
#     wyong.shp <- spTransform(wyong.shp,GDA94.56)

```

```{r functions}
shp2raster <- function(shp, mask.raster, label, value, bkg = 0,transform = FALSE, proj.from = NA, proj.to = NA, map = TRUE, save=TRUE,mask=TRUE) {
  require(raster, rgdal)
  
  # use transform==TRUE if the polygon is not in the same coordinate system as
  # the output raster, setting proj.from & proj.to to the appropriate
  # projections
  if (transform == TRUE) {
    if(is.na(proj4string(shp))) proj4string(shp) <- proj.from
    shp <- spTransform(shp, proj.to)
  }
  
  # convert the shapefile to a raster based on a standardised background raster with 
  # 'value' as the areas where the shapefile are and 'bkg' representing the areas outside the polygon
  r <- rasterize(shp, mask.raster,field=value,background=bkg)
    # mask out areas outside the boundary of the mask raster
    if(mask==T) r <- mask(r,mask.raster)
  
  # save a copy of the raster as a tif in the working directory
  if(save==TRUE) writeRaster(r, filename = label, format = "GTiff",overwrite = T)
    
  # plot map of new raster
  if (map == TRUE) plot(r, main = label, axes = F, box = F)
  
  names(r) <- label
  return(r)
}

addalpha <- function(colors, alpha=1.0) {
  r <- col2rgb(colors, alpha=T)
  # Apply alpha
  r[4,] <- alpha*255
  r <- r/255.0
  return(rgb(r[1,], r[2,], r[3,], r[4,]))
}


```

```{r load baseline data data}
# load curves files of the solution and find the fractions that mark protected areas
curves.baseline <- read.table(paste0(input.path, 'output_wyong.w5.curves.txt'), sep='')

# rank map
pri.baseline <- raster(paste0(input.path, 'output_wyong.w5_final.rank.compressed.tif'))

# breaks used to categorize cells
pri.baseline.breaks <- c(0, (1-top.fraction), 1)
  pri.baseline.breaks <- pri.baseline.breaks[order(pri.baseline.breaks)]
```

```{r plot baseline priority map}
png('baseline.priorities.w5.png', width = 11, height = 10, units="cm",res=300,bg="transparent",pointsize=12)

par(mfrow=c(1,1), mar=c(4,4,1,0), oma=c(0,0,0,0))
plot(bg, col=map.background, legend=F, axes=F, box=F)
plot(pri.baseline, breaks = pri.baseline.breaks, col=pri.col, add=T, legend=F, box=F)
plot(wyong.shp,add=T)
legend('bottom', inset=c(0,-0.18), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Conservation priority", cex=1, xpd=NA, horiz=T, title.adj=0)

dev.off()

```

```{r plot map backgrounds}
png('wyong_boundary.png', width = 11, height = 10, units="cm",res=300,bg="transparent",pointsize=12)
par(mfrow=c(1,1), mar=c(4,4,1,0), oma=c(0,0,0,0))
plot(wyong.shp,col="white")
dev.off()

Petaurus_norfolcensis_GH <- raster("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/extant/Petaurus_norfolcensis_SDM.GH.tif")
Petaurus_norfolcensis_wyong <- raster("//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Petaurus_norfolcensis_SDM_wyong.tif")
all.points <- read.csv(paste0('//654cw-20990/Amy/GIS_data/Hunter/Maxent_files/ghm.pm/species_data/maxent.data_mammals.csv'))
sp.points <- all.points[grepl("Petaurus norfolcensis",all.points$species),2:3]
coordinates(sp.points) <- c("x","y")
sp.points.GH <- sp.points[!is.na(extract(Petaurus_norfolcensis_GH,sp.points)),]
sp.points.wyong <- sp.points[!is.na(extract(Petaurus_norfolcensis_wyong,sp.points)),]

Antechinus_agilis_SSI_wyong <- raster("//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Antechinus_agilis_SSI_wyong.tif")
# Acianthus_exsertus.points <- all.points[grepl("Antechinus agilis",all.points$species),2:3]
ssi.points <- read.table("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/ssi_files/Antechinus agilis_GH.txt")
coordinates(ssi.points) <- c("V1","V2")
  ssi.points.wyong <- ssi.points[!is.na(extract(Petaurus_norfolcensis_wyong,ssi.points)),]

tuggerah.lakes <- raster("//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Tuggerah_Lakes_Saltmarsh_EEC.tif")

tiff('wyong_sdm_v2.tif', width = 20, height = 15, units="cm",res=300, compression='lzw', bg="transparent",pointsize=12)
#png('wyong_sdm_v2.png', width = 20, height = 15, units="cm",res=300,bg="transparent",pointsize=12)
# lay.out <- layout(matrix(c(1,2,3,3),byrow=T,2,2),heights=c(0.9,0.1))
par(mfrow=c(2,2),mar=c(1,1,1,1), oma=c(0,0,0,4),xpd=NA)
# plot(bg, col=map.background, legend=F, axes=F, box=F)
plot(Petaurus_norfolcensis_GH,col=blue2red(10),legend=F,box=F,axes=F,zlim=c(0,1000))
points(sp.points.GH,pch=1,cex=0.5,col=alpha("black",0.5))
plot(GH.shp,add=T,border="black",lwd=0.5)
plot(wyong.shp,add=T)
mtext("A",side=3,line=0,font=2,adj=0)
mtext("Squirrel Glider",side=3,line=0,font=1,adj=0.15,cex=0.8)
scalebar(50000,xy = c(197142,6282948),type = "line",label=c("50 km"),cex=0.75)

plot(bg, col=map.background, legend=F, axes=F, box=F)
plot(Petaurus_norfolcensis_wyong,col=blue2red(10),legend=F,box=F,axes=F,zlim=c(0,1000),add=T)
points(sp.points.wyong,pch=1,cex=0.5,col=alpha("black",0.5))
plot(wyong.shp,add=T)
mtext("B",side=3,line=0,font=2,adj=0)
mtext("Squirrel Glider",side=3,line=0,font=1,adj=0.15,cex=0.8)


# par(oma=c(0,0,0,1),mar=c(0,0,0,5))
image.plot(Petaurus_norfolcensis_wyong,small.plot=c(0,1,0,1),col=blue2red(10),legend.only=T,zlim=c(0,1000),axis.args = list(labels=c("Low","High"),at=c(0,1000),cex.axis=0.6),legend.args=list(text=paste0('Relative likelihood','\n','of occurrence'), side=3, font=2, line=2.5, cex=0.8),legend.shrink = 0.45)

# par(mar=c(1,1,1,1), oma=c(0,0,0,4))
plot(bg, col=map.background, legend=F, axes=F, box=F)
plot(Antechinus_agilis_SSI_wyong,col=c(NA,"grey30"),legend=F,box=F,axes=F,add=T,zlim=c(0,1))
plot(wyong.shp,add=T)
points(ssi.points.wyong,pch=21,cex=0.5,col="black",bg="darkgreen")
mtext("C",side=3,line=0,font=2,adj=0)
mtext("Agile Antechinus",side=3,line=0,font=1,adj=0.15,cex=0.8)
scalebar(10000,xy = c(332142.2,6303031),type = "line",label=c("10 km"),cex=0.75)

plot(bg, col=map.background, legend=F, axes=F, box=F)
plot(tuggerah.lakes,col=c(NA,"darkgreen","darkgreen"),legend=F,box=F,axes=F,add=T,zlim=c(0,1))
# points(ssi.points.wyong,pch=1,cex=0.5,col=alpha("black",0.5))
plot(wyong.shp,add=T)
mtext("D",side=3,line=0,font=2,adj=0)
mtext("Coastal Saltmarsh EEC",side=3,line=0,font=1,adj=0.15,cex=0.8)

dev.off()

tiff('wyong_remnant veg.tif', width = 20, height = 10, units="cm", compression='lzw', res=300,bg="transparent",pointsize=12)
#png('wyong_remnant veg.png', width = 20, height = 10, units="cm",res=300,bg="transparent",pointsize=12)
par(mfrow=c(1,2), mar=c(1,1,1,1), oma=c(0,0,0,0))
plot(Petaurus_norfolcensis_GH,col="darkgreen",legend=F,box=F,axes=F,zlim=c(0,1000))
  plot(GH.shp,add=T,border="grey20",lwd=1)
  plot(wyong.shp,add=T,lwd=2)
  mtext("A",side=3,line=0,font=2,adj=0)
  mtext("Greater Hunter",side=3,line=0,font=1,adj=0.15,cex=0.8)
  scalebar(50000,xy = c(197142,6282948),type = "line",label=c("50 km"),cex=0.75)

plot(bg,col=map.background,axes=F,legend=F,box=F)
  plot(veg.mask,col="darkgreen",add=T,legend=F)
  plot(wyong.shp,add=T)
  mtext("B",side=3,line=0,font=2,adj=0)
  mtext("Wyong Shire",side=3,line=0,font=1,adj=0.15,cex=0.8)
  scalebar(10000,xy = c(332142.2,6303031),type = "line",label=c("10 km"),cex=0.75)
dev.off()

```


```{r load PA data}
# load PA mask and calculate proportion of NPs and State Forests
PA <- raster('//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Mask files/PA_mask.tif')
np <- freq(PA)[3,2]/sum(freq(PA)[1:3,2])
sf <- freq(PA)[2,2]/sum(freq(PA)[1:3,2])

# load curves files of the solution and find the fractions that mark protected areas
curves.PA <- read.table(paste0(input.path, 'output_wyong_PAs_w5.curves.txt'), sep='')
protected.fraction <- curves.PA$V1[which(abs(curves.PA$V1-(1-(np+sf)))==min(abs(curves.PA$V1-(1-(np+sf)))))]
np.fraction <- curves.PA$V1[which(abs(curves.PA$V1-(1-(np)))==min(abs(curves.PA$V1-(1-(np)))))]

# rank map
pri.pa <- raster(paste0(input.path, 'output_wyong_PAs_w5.rank.compressed.tif'))

# breaks used to categorize cells
pri.breaks <- c(0, (protected.fraction-top.fraction), protected.fraction)
  pri.breaks <- pri.breaks[order(pri.breaks)]
pa.breaks = c(protected.fraction, np.fraction, 1)

# unprotected cells
pri <- pri.pa
pri[which(pri[] > protected.fraction)] <- NA

# protected cells
pa <- pri.pa
pa[which(pa[] < protected.fraction)] <- NA

```

```{r plot conservation priority map}

png('PA.expansion.priorities.w5.png', width = 11, height = 10, units="cm",res=300,bg="transparent",pointsize=12)

par(mfrow=c(1,1), mar=c(4,4,1,2), oma=c(0,0,0,0))
plot(bg, col=map.background, legend=F, axes=F, box=F)
plot(pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
plot(pa, breaks = pa.breaks, col=pa.col, add=T, legend=F, box=F)
legend('bottom', inset=c(0,-0.18), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Biodiversity priority", cex=1, xpd=NA, horiz=T, title.adj=0)

dev.off()

```

```{r plot development scenarios}
# import development masks
## Note that these currently have the vegetation removed
dev.planned <- raster('//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Mask files/Dev_planned.tif')
dev.leps <- raster('//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Mask files/Dev_LEPs_maj.tif')
dev.all <- raster('//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Mask files/Dev_all.tif')

dev.dir <- '//654cw-20990/Amy/GIS_data/Wyong/Wyong Shire Council Data/Planning/'

# Scenario 1 planned development
  CCRegionalAirportInvestigationArea_WSC_20140717 <- shapefile(paste0(dev.dir,"CCRegionalAirportInvestigationArea_WSC_20140717.shp"))
  WyongEmploymentZone_WSC_20140717 <- shapefile(paste0(dev.dir,"WyongEmploymentZone_WSC_20140717.shp"))
  UniversityPrecinctArea_WSC_20140717 <- shapefile(paste0(dev.dir,"UniversityPrecinctArea_WSC_20140717.shp"))
  BundeenaDev_WSC_20140721 <- shapefile(paste0(dev.dir,"BundeenaDev_WSC_20140721.shp"))
  JillibyStage2Dev.ProposedDev.WSC_20140721 <- shapefile(paste0(dev.dir,"JillibyStage2Dev(ProposedDev)_WSC_20140721.shp"))
  NorthWyongStructurePlanDevelopmentPrecincts21_WSC_20140717 <- shapefile(paste0(dev.dir,"NorthWyongStructurePlanDevelopmentPrecincts21_WSC_20140717.shp"))
  UrbanReleaseAreasWyongLEP2013_WSC_20140717 <- shapefile(paste0(dev.dir,"UrbanReleaseAreasWyongLEP2013_WSC_20140717.shp"))
  WarnervaleTownCentrePrecinctArea_WSC_20140717 <- shapefile(paste0(dev.dir,"WarnervaleTownCentrePrecinctArea_WSC_20140717.shp"))
  WestfieldDev.ProposedDev.WSC_20140721 <- shapefile(paste0(dev.dir,"WestfieldDev(ProposedDev)_WSC_20140721.shp"))

  airport <- shp2raster(CCRegionalAirportInvestigationArea_WSC_20140717,label="airport",bg,value=1,bkg=0,save=F)
  employment.zone <- shp2raster(WyongEmploymentZone_WSC_20140717,label="employment zone",bg,value=1,bkg=0,save=F)
  university <- shp2raster(UniversityPrecinctArea_WSC_20140717,label="university",bg,value=1,bkg=0,save=F)
  nw.structure.plan <- shp2raster(NorthWyongStructurePlanDevelopmentPrecincts21_WSC_20140717,label="nw.structure.plan",bg,value=1,bkg=0,save=F)
  urban.release <- shp2raster(UrbanReleaseAreasWyongLEP2013_WSC_20140717,label="urban.release",bg,value=1,bkg=0,save=F)
  town.centre <- shp2raster(WarnervaleTownCentrePrecinctArea_WSC_20140717,label="town.centre",bg,value=1,bkg=0,save=F)
  westfield <- shp2raster(WestfieldDev.ProposedDev.WSC_20140721,label="westfield",bg,value=1,bkg=0,save=F)

planned.development <- max(airport,employment.zone,university,nw.structure.plan,urban.release,town.centre,westfield)
  planned.development.veg <- sum(planned.development,veg.mask.0)

# Scenario 2 potential development
  ZoningWyongLEP2013_WSC_20140717 <- shapefile(paste0(dev.dir,"ZoningWyongLEP2013_WSC_20140717.shp"))
  LEP.zones <- read.csv(paste0(dev.dir,"LEP Biodiversity zoning table.csv"))
    developed.LEP.zones <- c(as.character(LEP.zones$X.[grepl("Mask",LEP.zones$Mask...Accept)]),"DM")

  potential.development <- shp2raster(ZoningWyongLEP2013_WSC_20140717[grepl(paste(developed.LEP.zones,collapse="|"),ZoningWyongLEP2013_WSC_20140717$Zone_Tag),],label="lep",bg,value=1,bkg=0,save=F)
  potential.development.veg <- sum(potential.development,veg.mask.0)

# Scenario 3 planned & potential development
  all.development <- max(planned.development,potential.development)
  all.development.veg <- sum(all.development,veg.mask.0)


tiff('Development_scenarios_veg.tif', width = 20, height = 7.5, units="cm",res=300, compression='lzw', bg="transparent",pointsize=10)
#png('Development_scenarios_veg.png', width = 20, height = 7.5, units="cm",res=300,bg="transparent",pointsize=10)

  par(mfrow=c(1,3), mar=c(1,1,1,0), oma=c(0,0,0,0))
  plot(bg, col='whitesmoke', legend=F, axes=F, box=F,main="Scenario 1")
    plot(veg.mask, col="lightgrey",add=T, legend=F, box=F)
    plot(planned.development.veg, breaks=c(0,0.5,1,1.5), col=c(NA,"grey40","black"), add=T, legend=F, box=F)
#     plot(planned.development, zlim=c(1,1), col="black", add=T, legend=F, box=F)
    mtext(line=-1,side=3,"Planned development",cex=0.7)

  plot(bg, col='whitesmoke', legend=F, axes=F, box=F, main="Scenario 2")
    plot(veg.mask, col="lightgrey",add=T, legend=F, box=F)
    plot(potential.development.veg, breaks=c(0,0.5,1,1.5), col=c(NA,"grey40","black"), add=T, legend=F, box=F)   
#     plot(potential.development, zlim=c(1,1), col="black", add=T, legend=F, box=F)
    mtext(line=-1,side=3,"Potential development",cex=0.7)
  
#   legend('bottom',  c("Planned","LEPs"), col=c("red","blue"), pch=15, bty="n", title="", cex=1, xpd=NA, horiz=T, title.adj=0)

  plot(bg, col='whitesmoke', legend=F, axes=F, box=F, main="Scenario 3")
    plot(veg.mask, col="lightgrey",add=T, legend=F, box=F)
    plot(all.development.veg, breaks=c(0,0.5,1,1.5), col=c(NA,"grey40","black"), add=T, legend=F, box=F)
#     plot(all.development, zlim=c(1,2), col="black", add=T, legend=F, box=F)
    mtext(line=-1,side=3,"Planned & potential development",cex=0.7)

dev.off()

```

```{r boxplots of development impacts}
dev.impacts <- read.csv('Species protection and anticipated development impact.csv')

tiff('development_impacts.tif', width = 15, height = 10, units="cm",res=300, compression='lzw', bg="transparent",pointsize=10)
#png('development_impacts.png', width = 15, height = 10, units="cm",res=300,bg="transparent",pointsize=10)
  
  par(las=1,mfrow=c(1,1), mar=c(4,14,1,1), oma=c(0,0,0,0))
  boxplot(dev.impacts$Dev.impact.All,dev.impacts$Dev.impact.LEP,dev.impacts$Dev.impact.Planned,horizontal=T,xlab="Proportion of feature distributions lost",names=c(paste("Scenario 3","\n","Planned & potential development"),paste("Scenario 2","\n","Potential development"), paste("Scenario 1","\n","Planned development")))

dev.off()

```

```{r boxplots of species protection}
sp.protection <- read.csv('PrioritizationResultsForBDFeatures_Wyong_UnprotectedPriorities_weight5.csv')

tiff('species protection.tif', width = 15, height = 10, units="cm",res=300, compression='lzw', bg="transparent",pointsize=10)
#png('species protection.png', width = 15, height = 10, units="cm",res=300,bg="transparent",pointsize=10)
  
  par(las=1,mfrow=c(1,1), mar=c(4,9,1,1), oma=c(0,0,0,0))
  boxplot(sp.protection$FinalProt.top30,sp.protection$FinalProt.top15,sp.protection$FinalProt.top10,sp.protection$FinalProt.top5,sp.protection$Protection.All,sp.protection$Protection.SF,sp.protection$Protection.NP,horizontal=T,xlab="Proportion of feature distributions protected",names=c("Top 30% added","Top 15% added","Top 10% added","Top 5% added","All protected areas","State Forests", "National Parks"),col=c("lightgrey","lightgrey","lightgrey","lightgrey","green4",pa.col[1],pa.col[2]))

dev.off()

```

```{r maps of conflicts btwn top priorities and development}

dev.planned.pri <- dev.planned
  dev.planned.pri[dev.planned.pri!=1] <- NA
  dev.planned.pri <- dev.planned.pri*pri

dev.leps.pri <- dev.leps
  dev.leps.pri[dev.leps.pri!=1] <- NA
  dev.leps.pri <- dev.leps.pri*pri

dev.all.pri <- dev.all
  dev.all.pri[dev.all.pri==3] <- NA
  dev.all.pri[!is.na(dev.all.pri)] <- 1
  dev.all.pri <- dev.all.pri*pri

dev.expansion.overlap <- data.frame(fraction=rev(top.fraction),dev.planned=NA,dev.leps=NA,dev.all=NA)

# for(i in seq(dev.expansion.overlap$fraction)){
#   dev.expansion.overlap$dev.planned[i] <- length(dev.planned.pri[dev.planned.pri>pri.breaks[i] & dev.planned.pri<=pri.breaks[i+1]])/length(pri[pri>pri.breaks[i] & pri<=pri.breaks[i+1]])
#    dev.expansion.overlap$dev.leps[i] <- length(dev.leps.pri[dev.leps.pri>pri.breaks[i] & dev.leps.pri<=pri.breaks[i+1]])/length(pri[pri>pri.breaks[i] & pri<=pri.breaks[i+1]])
#    dev.expansion.overlap$dev.all[i] <- length(dev.all.pri[dev.all.pri>pri.breaks[i] & dev.all.pri<=pri.breaks[i+1]])/length(pri[pri>pri.breaks[i] & pri<=pri.breaks[i+1]])
# }

for(i in seq(dev.expansion.overlap$fraction)){
  dev.expansion.overlap$dev.planned[i] <- length(dev.planned.pri[dev.planned.pri>pri.breaks[i]])/length(pri[pri>pri.breaks[i] ])
   dev.expansion.overlap$dev.leps[i] <- length(dev.leps.pri[dev.leps.pri>pri.breaks[i]])/length(pri[pri>pri.breaks[i] ])
   dev.expansion.overlap$dev.all[i] <- length(dev.all.pri[dev.all.pri>pri.breaks[i] ])/length(pri[pri>pri.breaks[i] ])
}

dev.expansion.overlap <- dev.expansion.overlap[order(dev.expansion.overlap$fraction),]
write.csv(dev.expansion.overlap,'Development-expansion overlap.csv',row.names=F)

tiff('Development_conflicts.tif', width = 11, height = 10, units="cm",res=300, compression='lzw', bg="transparent",pointsize=12)
#png('Development_conflicts.png', width = 11, height = 10, units="cm",res=300,bg="transparent",pointsize=12)

par(mfrow=c(1,1), mar=c(4,4,1,0), oma=c(0,0,0,0))

  plot(bg, col=map.background, legend=F, axes=F, box=F)
    plot(dev.all.pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
    plot(wyong.shp,add=T)
   

dev.off()

tiff('development.w5.tif', width = 20, height = 7.5, units="cm", compression='lzw', res=300,bg="transparent",pointsize=10)
#png('development.w5.png', width = 20, height = 7.5, units="cm",res=300,bg="transparent",pointsize=10)

  par(mfrow=c(1,3), mar=c(4,1,3,0), oma=c(0,0,0,0))

  plot(bg, col='whitesmoke', legend=F, axes=F, box=F, main="Scenario 1")
    plot(dev.planned.pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
    mtext(line=0,side=3,"Planned development",cex=0.7)  

  plot(bg, col='whitesmoke', legend=F, axes=F, box=F, main="Scenario 2")
    plot(dev.leps.pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
    mtext(line=0,side=3,"Potential development",cex=0.7)
  
  legend('bottom', inset=c(0.5,-0.18), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Biodiversity priority in development zones", cex=1, xpd=NA, horiz=T)

  plot(bg, col='whitesmoke', legend=F, axes=F, box=F, main="Scenario 3")
    plot(dev.all.pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
    mtext(line=0,side=3,"Planned & potential development",cex=0.7)

dev.off()


```

```{r overlays of costs on priorities}
## Neither of the outputs of these costing options make any sense!

cost.col <- addalpha(rep("black",100),seq.int(0, 1, length.out=100))

# costs.shp <- readShapePoly("//654cw-20990/Amy/GIS_data/Wyong/Wyong Shire Council Data/Cost/cadastre_with_rate_value.shp",proj4string = GDA94.56)
#   costs.shp$area <- gArea(costs.shp,byid=T)
#   costs.shp$cost.ha <- costs.shp$RATEVALUE/costs.shp$area
# cost.ha <- shp2raster(costs.shp,bg,"Wyong Shire Council Data/Cost/cost.per.ha.tif",value=costs.shp$cost.ha)
# cost <- shp2raster(costs.shp,bg,"Wyong Shire Council Data/Cost/cost.tif",value=costs.shp$RATEVALUE)

cost.mask <- raster("Wyong Shire Council Data/Cost/cost.per.ha.tif")
#   cost.mask[cost.mask<1] <- NA
test <- cost.mask*pri

pri.top <- pri
pri.top[which(pri.top[] < pri.breaks[2])] <- NA

pri.cost <- pri.top/(cost.mask+0.001)
  pri.cost <- pri.cost/cellStats(pri.cost,max)
writeRaster(pri.cost, 'cost.efficiency.top.pri.tif', type='GTiff', over.write=T)
pri.cost <- raster('cost.efficiency.top.pri.tif')

png('cost of priorities.png', width = 11, height = 10, units="cm",res=300,bg="transparent",pointsize=10)

par(mfrow=c(1,1), mar=c(4,1,1,0), oma=c(0,0,0,0))
plot(bg, col=map.background, legend=F, axes=F, box=F)
  plot(pri, col="grey30", add=T, legend=F, box=F)
plot(pri.cost,  add=T, box=F,legend=F)
  image.plot(add = T,legend.only=T,zlim=c(0,1),axis.args=list(at=c(0,1),labels=c("Low","High"), cex.axis=0.6),legend.args=list(text='Cost efficiency', side=3, cex=0.6,adj=0),horizontal=T,smallplot=c(0.41,0.61,0.1,0.12),col=rev(terrain.colors(100)))
#   legend('bottom', inset=c(0,-0.18), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Conservation priority", cex=1, xpd=NA, title.adj=0)

dev.off()


tiff('priorities & cost of priorities_v2.tiff', width = 20, height = 10, units="cm",res=300, compression='lzw', bg="transparent",pointsize=12)
#png('priorities & cost of priorities_v2.png', width = 20, height = 10, units="cm",res=300,bg="transparent",pointsize=12)
par(mfrow=c(1,2), mar=c(0,0,0,0), oma=c(4,0.2,1,0),xpd=NA)
plot(bg, col=map.background, legend=F, axes=F, box=F)
  plot(pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
  plot(pa, breaks = pa.breaks, col=pa.col, add=T, legend=F, box=F)
  legend('bottom', inset=c(0,-0.16), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Biodiversity priority", cex=0.6, xpd=NA, horiz=T, title.adj=0)
mtext(side=3,font=2,"A",line=0,adj=0)

plot(bg, col=map.background, legend=F, axes=F, box=F)
  plot(pri.top, col="grey30", add=T, legend=F, box=F)
  plot(pri.cost,  col=brewer.pal(9,"YlOrRd"),add=T, box=F,legend=F)
#   plot(pa, breaks = pa.breaks, col=pa.col, add=T, legend=F, box=F)
mtext(side=3,font=2,"B",line=0,adj=0)

par(oma=c(1,0,0,0))
image.plot(add = T,legend.only=T,zlim=c(0,1),axis.args=list(at=c(0,1),labels=c("Low","High"),cex.axis=0.6),legend.args=list(text='Cost efficiency', side=3, cex=0.6,adj=0),horizontal=T,smallplot=c(0.31,0.71,0.1,0.12),col=brewer.pal(9,"YlOrRd"))

dev.off()

# calculate the cumulative sum of the cost.per.ha within the top priority sites
costs <- data.frame(Fraction=top.fraction,Area=c(length(cost.mask[pri>pri.breaks[5]]),length(cost.mask[pri>pri.breaks[4]]),length(cost.mask[pri>pri.breaks[3]]),length(cost.mask[pri>pri.breaks[2]])),Cost=c(sum(cost.mask[pri>pri.breaks[5]],na.rm=T),sum(cost.mask[pri>pri.breaks[4]],na.rm=T),sum(cost.mask[pri>pri.breaks[3]],na.rm=T),sum(cost.mask[pri>pri.breaks[2]],na.rm=T)))



# calculate the cumulative sum of the costs of polygons overlapping with the top priority sites
top5.points <- rasterToPoints(pri,fun=function(x){x>pri.breaks[5]},spatial=T)
  proj4string(top5.points) <- GDA94.56
top5.poly <- over(top5.points,costs.shp)
costs.shp$top5 <- NA
costs.shp$top5[costs.shp$OBJECTID %in% top5.poly$OBJECTID] <- 1

top10.points <- rasterToPoints(pri,fun=function(x){x>pri.breaks[4]},spatial=T)
  proj4string(top10.points) <- GDA94.56
top10.poly <- over(top10.points,costs.shp)
costs.shp$top10 <- NA

costs.shp$top10[costs.shp$OBJECTID %in% top10.poly$OBJECTID] <- 1

top15.points <- rasterToPoints(pri,fun=function(x){x>pri.breaks[3]},spatial=T)
  proj4string(top15.points) <- GDA94.56
top15.poly <- over(top15.points,costs.shp)
costs.shp$top15 <- NA

costs.shp$top15[costs.shp$OBJECTID %in% top15.poly$OBJECTID] <- 1

sum(top5.poly$RATEVALUE,na.rm=T)
sum(top10.poly$RATEVALUE,na.rm=T)
sum(top15.poly$RATEVALUE,na.rm=T)

```


```{r species of special interest}

# species <- c("Angophora_inopina","Acacia_bynoeana","Grevillea_parviflora","Rutidosis_heterogama","Tetratheca_juncea","Petaurus_norfolcensis","Regent_honeyeater_habitat","Swift_parrot_habitat")
# 
# spp.list <- read.table("//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/wyong.zonation.w5.spp")
# 
# special.sp <- spp.list$V6[grepl(paste0(species,collapse="|"),spp.list$V6)]
# 
# # load curves files of the solution and find the fractions that mark protected areas
# curves.baseline <- read.table(paste0(input.path, 'output_wyong.w5.curves.txt'), sep='')
#    colnames(curves.baseline) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2',as.character(spp.list$V6))
# 
# pa.curves <- read.table(paste0(input.path, 'output_wyong_PAs_w5.curves.txt',sep=' '))
#   colnames(pa.curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2',as.character(spp.list$V6))
# 
# devLEPs.curves <- read.table(paste0(input.path, 'output_wyong_DevLEPs.curves.txt',sep=' '))
#   colnames(devLEPs.curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2',as.character(spp.list$V6))
# 
# devPlanned.curves <- read.table(paste0(input.path, 'output_wyong_DevPlanned.curves.txt',sep=' '))
#   colnames(devPlanned.curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2',as.character(spp.list$V6))
# 
# devall.curves <- read.table(paste0(input.path, 'output_wyong_DevAll.curves.txt',sep=' '))
#   colnames(devall.curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2',as.character(spp.list$V6))
# 
# special.sp.table <- d(matrix(NA,14,10))
# colnames(special.sp.table) <- c("Scenario","fraction",as.character(species))
# 
# for(i in 2:5){
#   special.sp.table$Scenario[i] <- "Top priority"
#   special.sp.table$fraction[i] <- 1-pri.baseline.breaks[i]
#   special.sp.table[i,3:10] <- curves.baseline[which(curves.baseline$Prop_landscape_lost>pri.baseline.breaks[i])[1],match(special.sp,colnames(curves.baseline))]
#   
# }
# 
# for(i in 1:2){
#   special.sp.table$Scenario[i+5] <- "Protected Areas"
#   special.sp.table$fraction[i+5] <- pa.breaks[i]
#   special.sp.table[i+5,3:10] <- pa.curves[which(pa.curves$Prop_landscape_lost>pri.baseline.breaks[i])[1],match(special.sp,colnames(pa.curves))]
#   
# }
# 
# for(i in 2:5){
#   special.sp.table$Scenario[i+6] <- "Priority Sites outside PA"
#   special.sp.table$fraction[i+6] <- protected.fraction-pri.breaks[i]
#   special.sp.table[i+6,3:10] <- pa.curves[which(pa.curves$Prop_landscape_lost>pri.breaks[i])[1],match(special.sp,colnames(pa.curves))]
#   
# }
# 
# # Impacts of development
# 
# special.sp.table$Scenario[12:14] <- c("LEPs","Planned","All")
# special.sp.table[12:14,3:10] <- t(dev.impacts[match(gsub("_"," ",gsub("_SDM_wyong|\\.tif","",special.sp)),dev.impacts$Scientific.Name),c("Dev.impact.Planned","Dev.impact.LEP","Dev.impact.All")])
# 
# special.sp.table <- special.sp.table[-1,]
# 
# write.csv(special.sp.table,paste0(input.path,"Special Species Summary.csv"),row.names=F)

```

```{r horrenda table}

horrenda.table <- read.csv("//654cw-20990/Amy/GIS_data/Wyong/PrioritizationResultsForBDFeatures_Wyong_UnprotectedPriorities_weight5.csv")

data.type <- read.csv("//654cw-20990/Amy/GIS_data/Wyong/PrioritizationResultsForBDFeatures_Wyong_weighted2.csv")
results <- read.csv("//654cw-20990/Amy/GIS_data/Wyong/Species protection and anticipated development impact.csv")

spp.list <- read.table("//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/wyong.zonation.w5.spp")
SDM.species <- gsub("_"," ",gsub("_SDM_wyong|\\.tif","",spp.list$V6[grepl("SDM",spp.list$V6)]))
SSI.species <- gsub("_"," ",gsub("_SSI_wyong|\\.tif","",spp.list$V6[grepl("SSI",spp.list$V6)]))

horrenda.table$DistributionSize[match(SDM.species,horrenda.table$Scientific.Name)] <- (horrenda.table$DistributionSize[match(SDM.species,horrenda.table$Scientific.Name)]/1000)

horrenda.table$DistributionSize <- horrenda.table$DistributionSize/52769

horrenda.table$DataType <- data.type$Data.type[match(horrenda.table$Scientific.Name,data.type$Scientific.Name)]
horrenda.table$DataSource <- data.type$Data.source[match(horrenda.table$Scientific.Name,data.type$Scientific.Name)]

horrenda.table$Dev.impact.Planned <- results$Dev.impact.Planned[match(horrenda.table$Scientific.Name,results$Scientific.Name)]
horrenda.table$Dev.impact.LEP <- results$Dev.impact.LEP[match(horrenda.table$Scientific.Name,results$Scientific.Name)]
horrenda.table$Dev.impact.All <- results$Dev.impact.All[match(horrenda.table$Scientific.Name,results$Scientific.Name)]

input.horrenda.table <- horrenda.table[with(horrenda.table,order(Taxa,Scientific.Name)),c("Taxa","Scientific.Name","Common.Name","mnes","NSW.status","Comm.status","DataSource","DataType","DistributionSize")]

write.csv(input.horrenda.table,"input.horrenda.table.csv",row.names=F)

results.horrenda.table <- horrenda.table[with(horrenda.table,order(Taxa,Scientific.Name)),c("Taxa","Scientific.Name","Common.Name","Protection.NP","Protection.SF","Protection.All","FinalProt.top5","FinalProt.top10","FinalProt.top15","FinalProt.top30","Dev.impact.Planned","Dev.impact.LEP","Dev.impact.All")]

write.csv(results.horrenda.table,"results.horrenda.table.csv",row.names=F)

```

```{r overlap of expansion priorities & council owned land}

CouncilOwnedProperty_WSC_20140717 <- shapefile("//654cw-20990/Amy/GIS_data/Wyong/Wyong Shire Council Data/Tenure/CouncilOwnedProperty(s)_WSC_20140717.shp")
CrownProperty_WSC_20140717 <- shapefile("//654cw-20990/Amy/GIS_data/Wyong/Wyong Shire Council Data/Tenure/CrownProperty(s)_WSC_20140717.shp")

council.land <- shp2raster(CouncilOwnedProperty_WSC_20140717,label="council land",bg,value=1,bkg=0,save=F)
crown.land <- shp2raster(CrownProperty_WSC_20140717,label="crown land",bg,value=1,bkg=0,save=F)

council.land.pri <- council.land
  council.land.pri[council.land.pri!=1] <- NA
  council.land.pri <- council.land.pri*pri

crown.land.pri <- crown.land
  crown.land.pri[crown.land.pri!=1] <- NA
  crown.land.pri <- crown.land.pri*pri

tiff('expansion-council land.tif', width = 20, height = 10, units="cm",res=300, compression='lzw', bg="transparent",pointsize=12)
#png('expansion-council land.png', width = 20, height = 10, units="cm",res=300,bg="transparent",pointsize=12)

  par(mfrow=c(1,2), mar=c(3,0,1,0), oma=c(0,0,0,0))

  plot(bg, col='whitesmoke', legend=F, axes=F, box=F)
    plot(council.land.pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
    plot(wyong.shp,add=T)
    mtext(line=0,side=3,"A",adj=0,font=2)  

  legend('bottom', inset=c(0.75,-0.16), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Biodiversity priority", cex=0.6, xpd=NA, horiz=T, title.adj=0)

  plot(bg, col='whitesmoke', legend=F, axes=F, box=F)
    plot(crown.land.pri, breaks = pri.breaks, col=pri.col, add=T, legend=F, box=F)
    plot(wyong.shp,add=T)
    mtext(line=0,side=3,"B",adj=0,font=2)

dev.off()

tenure.expansion.overlap <- data.frame(fraction=rev(top.fraction),council.land=NA,council.land=NA)

# for(i in seq(dev.expansion.overlap$fraction)){
#   dev.expansion.overlap$dev.planned[i] <- length(dev.planned.pri[dev.planned.pri>pri.breaks[i] & dev.planned.pri<=pri.breaks[i+1]])/length(pri[pri>pri.breaks[i] & pri<=pri.breaks[i+1]])
#    dev.expansion.overlap$dev.leps[i] <- length(dev.leps.pri[dev.leps.pri>pri.breaks[i] & dev.leps.pri<=pri.breaks[i+1]])/length(pri[pri>pri.breaks[i] & pri<=pri.breaks[i+1]])
#    dev.expansion.overlap$dev.all[i] <- length(dev.all.pri[dev.all.pri>pri.breaks[i] & dev.all.pri<=pri.breaks[i+1]])/length(pri[pri>pri.breaks[i] & pri<=pri.breaks[i+1]])
# }

for(i in seq(tenure.expansion.overlap$fraction)){
  tenure.expansion.overlap$council.land[i] <- length(council.land.pri[council.land.pri>pri.breaks[i]])/length(pri[pri>pri.breaks[i] ])
   tenure.expansion.overlap$council.land[i] <- length(council.land.pri[council.land.pri>pri.breaks[i]])/length(pri[pri>pri.breaks[i] ])
}

tenure.expansion.overlap <- tenure.expansion.overlap[order(tenure.expansion.overlap$fraction),]
write.csv(tenure.expansion.overlap,'Tenure-expansion overlap.csv',row.names=F)


```


```{r A3 maps & data files for Wyong Council}


pdf('conservation.priorities_A3_categories.pdf', width=16.53,height=11.69,pointsize=16)

  par(mfrow=c(1,1), mar=c(2,2,2,0), oma=c(4,4,4,4),xpd=NA)
  plot(bg, col=map.background, legend=F, axes=F, box=F)
  plot(pri, breaks = pri.breaks[2:6], col=pri.col[2:5], add=T, legend=F, box=F)
  plot(wyong.shp,add=T)
  legend('bottomright', inset=c(0,0), legend=c("very high","high","moderately high", "moderate"), col=rev(pri.col), pch=15, bty="n", cex=1.5,xpd=T, title.adj=0)
  # legend('bottom', inset=c(0,-0.18), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Conservation priority", cex=1, xpd=NA, horiz=T, title.adj=0)
  mtext(paste0("This map is an output of the modelling study undertaken by The University of Melbourne (2015),","\n"," commissioned as part of the Strategic Development Lands Biodiversity Certification Assessment.","\n"," High environmental value areas are priorities for site surveys to determine offset credit value."),side=1,cex=1.25, line =4)
  mtext(side=3,"Environmental value based on all flora and fauna species",cex=1.5,font=2,line=3)

dev.off()

pdf('conservation.priorities_A3_values.pdf', width=16.53,height=11.69,pointsize=16)

  par(mfrow=c(1,1), mar=c(2,2,2,0), oma=c(4,4,4,4),xpd=NA)
  plot(bg, col=map.background, legend=F, axes=F, box=F)
  plot(pri, breaks = pri.breaks[2:6], col=pri.col[2:5], add=T, legend=F, box=F)
  plot(wyong.shp,add=T)
  legend('bottomright', inset=c(0,0), legend=c("Top 5%","Top 10%","Top 15%", "Top 30%"), col=rev(pri.col), pch=15, bty="n", cex=1.5,xpd=T, title.adj=0)
  # legend('bottom', inset=c(0,-0.18), leg.labels, col=rev(pri.col), pch=15, bty="n", title="Conservation priority", cex=1, xpd=NA, horiz=T, title.adj=0)
  mtext(paste0("This map is an output of the modelling study undertaken by The University of Melbourne (2015),","\n"," commissioned as part of the Strategic Development Lands Biodiversity Certification Assessment.","\n"," High environmental value areas are priorities for site surveys to determine offset credit value."),side=1,cex=1.25, line =4)
  mtext(side=3,"Environmental value based on all flora & fauna species",cex=1.5,font=2,line=3)

dev.off()

# tif files for Wyong council

# data from fig 10A - expansion priorities
pri.10A <- pri
  pri.10A <- pri.10A + (1-pa.breaks[1])
writeRaster(pri.10A,"Biodiversity Priorities Wyong LGA April 2015/Conservation_expansion_priorities_Fig10A_continuous.tif",overwrite=T)

# Fix the tiny error in values
pri.10A <- raster("Biodiversity Priorities Wyong LGA April 2015/Conservation_expansion_priorities_Fig10A_continuous.tif")
pri.10A <- pri.10A*1
gap <- 1-max(pri.10A@data@values, na.rm=T)
pri.10A <- pri.10A+gap
plot(pri.10A)
writeRaster(pri.10A,"Biodiversity Priorities Wyong LGA April 2015/Conservation_expansion_priorities_Fig10A_continuous.tif",overwrite=T)



pri.10A.cat <- pri.10A
  pri.10A.cat[pri.10A.cat<pri.baseline.breaks[2]] <- NA
  pri.10A.cat[pri.10A.cat<pri.baseline.breaks[3]] <- 30
  pri.10A.cat[pri.10A.cat<pri.baseline.breaks[4]] <- 15
  pri.10A.cat[pri.10A.cat<pri.baseline.breaks[5]] <- 10
  pri.10A.cat[pri.10A.cat<(pri.baseline.breaks[6]+1)] <- 5 # the +1 is needed to include the one cell with value of 1
writeRaster(pri.10A.cat,"Biodiversity Priorities Wyong LGA April 2015/Conservation_expansion_priorities_Fig10A_catergorical.tif",overwrite=T)


# data from Fig 11 - top priorities in council/council lands
crown.land.pri.11 <- crown.land.pri
  crown.land.pri.11 <- crown.land.pri.11 + (1-pa.breaks[1])
writeRaster(crown.land.pri.11,"Biodiversity Priorities Wyong LGA April 2015/Crown_land_expansion_priorities_Fig11B_continuous.tif",overwrite=T)

# Fix the tiny error in values
crown.land.pri.11 <- raster("Biodiversity Priorities Wyong LGA April 2015/Crown_land_expansion_priorities_Fig11B_continuous.tif")*1
gap <- 1-max(crown.land.pri.11@data@values, na.rm=T)
crown.land.pri.11 <- crown.land.pri.11+gap
plot(crown.land.pri.11)
writeRaster(crown.land.pri.11,"Biodiversity Priorities Wyong LGA April 2015/Crown_land_expansion_priorities_Fig11B_continuous.tif",overwrite=T)
  
crown.land.pri.11.cat <- crown.land.pri.11
  crown.land.pri.11.cat[crown.land.pri.11.cat<pri.baseline.breaks[2]] <- NA
  crown.land.pri.11.cat[crown.land.pri.11.cat<pri.baseline.breaks[3]] <- 30
  crown.land.pri.11.cat[crown.land.pri.11.cat<pri.baseline.breaks[4]] <- 15
  crown.land.pri.11.cat[crown.land.pri.11.cat<pri.baseline.breaks[5]] <- 10
  crown.land.pri.11.cat[crown.land.pri.11.cat<pri.baseline.breaks[6]+1] <- 5
writeRaster(crown.land.pri.11.cat,"Biodiversity Priorities Wyong LGA April 2015/Crown_land_expansion_priorities_Fig11B_catergorical.tif",overwrite=T)

council.land.pri.11 <- council.land.pri
  council.land.pri.11 <- council.land.pri.11 + (1-pa.breaks[1])
writeRaster(council.land.pri.11,"Biodiversity Priorities Wyong LGA April 2015/Council_land_expansion_priorities_Fig11A_continuous.tif",overwrite=T)

# Fix the tiny error in values
council.land.pri.11 <- raster("Biodiversity Priorities Wyong LGA April 2015/council_land_expansion_priorities_Fig11A_continuous.tif")*1
gap <- 1-max(council.land.pri.11@data@values, na.rm=T)
council.land.pri.11 <- council.land.pri.11+gap
plot(council.land.pri.11)
writeRaster(council.land.pri.11,"Biodiversity Priorities Wyong LGA April 2015/Council_land_expansion_priorities_Fig11A_continuous.tif",overwrite=T)

council.land.pri.11.cat <- council.land.pri.11
  council.land.pri.11.cat[council.land.pri.11.cat<pri.baseline.breaks[2]] <- NA
  council.land.pri.11.cat[council.land.pri.11.cat<pri.baseline.breaks[3]] <- 30
  council.land.pri.11.cat[council.land.pri.11.cat<pri.baseline.breaks[4]] <- 15
  council.land.pri.11.cat[council.land.pri.11.cat<pri.baseline.breaks[5]] <- 10
  council.land.pri.11.cat[council.land.pri.11.cat<pri.baseline.breaks[6]+1] <- 5
writeRaster(council.land.pri.11.cat,"Biodiversity Priorities Wyong LGA April 2015/Council_land_expansion_priorities_Fig11A_catergorical.tif",overwrite=T)

# Unweighted and weighted unconstrained priorities

pri.unw <- raster('//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Output/output_wyong_final.rank.compressed.tif')
plot(pri.unw)
writeRaster(pri.unw, 'Biodiversity Priorities Wyong LGA April 2015/Conservation_priorities_Wyong_Fig8A_unweighted_continuous.tif', format='GTiff', overwrite=T)

pri.w5 <- raster('//654cw-20990/Amy/GIS_data/Hunter/zonation/wyong/Output/output_wyong.w5_final.rank.compressed.tif')
plot(pri.w5)
writeRaster(pri.unw, 'Biodiversity Priorities Wyong LGA April 2015/Conservation_priorities_Wyong_Fig8B_weightedx5_continuous.tif', format='GTiff', overwrite=T)


```


