---
title: "Clip to Port MacQuarie bunadary"
author: "Amy Whitehead"
date: "Thursday, March 05, 2015"
output: html_document
---

```{r}
rm(list=ls())

library(raster)
library(maptools)

#computer <- "~" #My computer
computer <- "Z:/Amy" #Super computer
# computer <- "//654cw-20990/Amy"

# directories
# location of GH files
  maxent.dir <- paste0(computer,"/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/")

# location of PM files
  PM.zonation.dir <- paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/") 

# GH zonation directory
  GH_PM.zonation.dir <- paste0(computer,"/GIS_data/Hunter/zonation/GH_PM/extant/")

# Use updated bird SDMs from pre1750v3_PMHC
  new.birds <- TRUE

# set projections
  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# import region mask for PM
 PM.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/PM.mask.tif"))
  PM.mask[!is.na(PM.mask)] <- 0

# PM clipping mask
  PM.clipping.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/PM.clipping.mask.tif"))
    PM.clipping.mask[!is.na(PM.clipping.mask)] <- 0

# open species list
  protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))
    protected.species$PM.sdm <- NA
    levels(protected.species$PM.sdm) <- c(NA,"SDM","SSI")

# open tec list
  tec.data <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/GreaterHunter_DRAFT_100812 (2).csv"))
    tec.data$PM.points <- NA
    tec.data$PM.sdm <- NA

# delete all existing tifs in port macquarie folder
## only run this if you definitely want to delete these files!!
tifs <- dir(PM.zonation.dir, pattern=".PM.tif$",full.names=T)
# file.remove(tifs)

taxa <- c("amphibians","birds","mammals","reptiles","plants")

```

```{r clip to PM}
# function to clip to PM region
#   clip.to.PM <- function(tiff, mask.raster){
#     r <- raster(paste0(GH.zonation.dir,"extant/",tiff,"_GH.tif"),crs=GDA94.56)
#     
#     if(cellStats(r,max,na.rm=T) > 1){
#       r <- mask(crop(r,mask.raster),mask.raster,filename=paste0(PM.zonation.dir,tiff,"_SDM_PM.tif"),format="GTiff",overwrite=T)
#       cat("Clipped",as.character(tiff),"to PM","\n")}
#   }


clip.to.PM <- function (asc.file,mask.raster) {
    r <- raster(asc.file)
    species <- gsub("_SDM.GH_PM.tif|Z:/|//654cw-20990/|Amy/GIS_data/Hunter/zonation/GH_PM/extant/|Amy/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/birds/pre1750v3_PMHC/Full/|\\.asc","",asc.file)
    r <- mask(crop(r,mask.raster),mask.raster)
    if(cellStats(r,max)<1) r <- r*1000
    writeRaster(r,paste0(PM.zonation.dir,as.character(species),"_SDM.PM.tif"), overwrite=T, datatype='INT2U')
#     cat(" clipped",as.character(species), "to PM","\n")
  }

```


```{r presence.absence.raster function}
    
presence.absence.raster <- function (mask.raster,species.data,raster.label="") {
    #set the cells that contain points to 1
  speciesRaster <- rasterize(species.data,mask.raster,field=1)
    if(cellStats(speciesRaster,max)>0){
    speciesRaster <- mask(merge(speciesRaster,mask.raster),mask.raster)
    #label the raster
    names(speciesRaster) <- raster.label
    writeRaster(speciesRaster,paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/",raster.label,"_SSI.PM.tif"), format="GTiff",overwrite=T)
  cat("Converted",as.character(raster.label),"to raster","\n")
  }
  gc()
}

```

Clip species

```{r identify maxent species within PM}
# import maxent point data for GH data
  maxent.data <- read.csv(paste0(computer,"/GIS_data/Hunter/Maxent_files/ghm.pm/species_data/maxent.data_ALA.NSW.csv"))
#     colnames(maxent.data) <- c("easting","northing","species")

# maxent.summary <- read.csv(paste0(computer,"/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/GH DotE report - maxent summary.csv"))
maxent.summary <- read.csv(paste0(computer,"/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/GH DotE report - maxent summary.v3_PMHC.csv"))

# create list of unique MaxEnt species
  me.species <- data.frame(species=unique(maxent.data$species),AUC=NA,in.GH=NA,in.PM=NA,GH.max=NA,PM.max=NA)

# loop through each species, identify which has points in PM and return list
  for(i in seq(me.species$species)){
    s <- maxent.data[maxent.data$species==me.species$species[i],]
    me.species$in.GH[i] <- nrow(s)
    
    # identify points within region
    in.PM <- length(which(!is.na(extract(PM.clipping.mask,s[,c("easting","northing")]))))
     me.species$AUC[i] <- maxent.summary$Test.AUC[grepl(me.species$species[i],maxent.summary$Species)]
    
    if(in.PM>0) {
      me.species$in.PM[i] <- "TRUE"
      cat(as.character(me.species$species[i]),"has", in.PM, "points in PM","\n")
      protected.species$PM[protected.species$Scientific.Name==as.character(me.species$species[i])] <- in.PM
        } else me.species$in.PM[i] <- "FALSE"
  }

```

```{r clip maxent output for species with points in PM}
# location of PM files
  PM.zonation.dir <- paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/")

# create list of PM species to clip
  PM.tifs <- me.species$species[which(me.species$in.PM == TRUE & me.species$AUC>0.7) ]
    PM.tifs <- gsub(" ","_",PM.tifs)

# clip the remaining taxa from already clipped models
taxa <- c("amphibians","mammals","reptiles","plants")

 pb.species <- txtProgressBar(min=0,max=length(asc.files),initial=0,style=3)

for(j in seq(PM.tifs)){  
    species <- PM.tifs[j] 
      species <- gsub("_"," ",species)  
    
    tryCatch({
      clip.to.PM(paste0(GH_PM.zonation.dir,PM.tifs[j],"_SDM.GH_PM.tif"),PM.clipping.mask)
      me.species[me.species$species==as.character(species),"GH.max"] <- cellStats(raster(paste0(GH_PM.zonation.dir,PM.tifs[j],"_SDM.GH_PM.tif"),crs=GDA94.56),max)/1000
      me.species[me.species$species==as.character(species),"PM.max"] <- cellStats(raster(paste0(PM.zonation.dir,PM.tifs[j],"_SDM.PM.tif"),crs=GDA94.56),max)/1000
      
      if(me.species[me.species$species==as.character(species),"GH.max"]*1000 > 1){
        protected.species$PM.sdm[protected.species$Scientific.Name==as.character(species)] <- "SDM"
      }
    }, error=function(err) cat(""),warning=function(war) cat("Check",PM.tifs[j],"for missing tif","\n"))
  setTxtProgressBar(pb.species,j)
  }

close(pb.species)

if(new.birds==TRUE) {
  
# clip from original MaxEnt outputs (birds only)
  taxa <- "birds"
  
  for(i in seq(taxa)){
    cat("Converting",taxa[i],"\n")
    asc.files <- dir(paste0(maxent.dir,taxa[i],"/pre1750v3_PMHC/Full/"), pattern=".asc$")
      asc.files <- asc.files[!grepl("pre1750",asc.files)]
      asc.files <- asc.files[asc.files %in% paste0(PM.tifs,".asc")]
  
    pb.species <- txtProgressBar(min=0,max=length(asc.files),initial=0,style=3)
    
    for(j in seq(asc.files)){  
      species <- asc.files[j] 
        species <- gsub("_"," ",gsub("\\.asc","",species))
      
      tryCatch({
        clip.to.PM(paste0(maxent.dir,taxa[i],"/pre1750v3_PMHC/Full/",asc.files[j]),PM.clipping.mask)
        me.species[me.species$species==as.character(species),"GH.max"] <- cellStats(raster(paste0(maxent.dir,taxa[i],"/pre1750v3_PMHC/Full/",asc.files[j]),crs=GDA94.56),max)
        me.species[me.species$species==as.character(species),"PM.max"] <- cellStats(raster(paste0(PM.zonation.dir,gsub("\\.asc","",asc.files[j]),"_SDM.PM.tif")),max)/1000
        
        if(me.species[me.species$species==as.character(species),"GH.max"]*1000 > 1){
          protected.species$PM.sdm[protected.species$Scientific.Name==as.character(species)] <- "SDM"
        }
      }, error=function(err) cat(""),warning=function(war) cat("Check",PM.tifs[j],"for missing tif"))
    setTxtProgressBar(pb.species,j)
    
    }
    
    close(pb.species)
  }
}


# save species list output for future use
  write.csv(me.species,paste0(PM.zonation.dir,"maxent_species.list.csv"),row.names=F)

```


```{r identify species with low AUC scores in PM and convert to SSI}
 threshold <- 0.7

# identify species that have low SDM values within PMHC
  species.list <- as.character(me.species$species[me.species$PM.max/me.species$GH.max<0.25])
    species.list <- species.list[!is.na(species.list)]
  # add those species that seem to be missing SDMs  
    species.list <- unique(append(as.character(species.list),as.character(me.species$species[me.species$in.PM==TRUE & is.na(me.species$GH.max) & me.species$in.GH<100],me.species$species[me.species$AUC < threshold & me.species$in.GH<100])))

  
# create presence-absence rasters for species with low SDM values 
    if(length(species.list)>0){
     
      for(i in seq(species.list)){
        
        species.data <- maxent.data[maxent.data$species == species.list[i],]
        species.data <- species.data[,c("easting","northing")]
        species <- gsub(" ","_",species.list[i])
        presence.absence.raster(PM.clipping.mask,species.data, raster.label=species)
        try({
            file.remove(paste0(PM.zonation.dir,species,"_SDM.PM.tif"))
            cat("Removed",paste0(species,"_SDM.PM.tif","\n"))
            },silent=T)
        species <- gsub("_"," ",species)
        protected.species$PM.sdm[protected.species$Scientific.Name==as.character(species)] <- "SSI"
      }
    }

# save species list output for future use
  write.csv(me.species,paste0(PM.zonation.dir,"maxent_species.list.csv"),row.names=F)

# remove species with poor AUC values & more than 100 points
species.list <- as.character(me.species$species[me.species$AUC < threshold & me.species$in.GH>100])
for(i in seq(species.list)){
  try({
            file.remove(paste0(PM.zonation.dir,gsub(" ","_",species.list[i]),"_SDM.PM.tif"))
            cat("Removed",paste0(gsub(" ","_",species.list[i]),"_SDM.PM.tif","\n"))
            },silent=T)
}

```


```{r create species SSI tifs}
me.species <- read.csv(paste0(PM.zonation.dir,"maxent_species.list.csv"))
  ssi.dir <- paste0(computer,"/GIS_data/Hunter/zonation/GH_PM/SSI/")

  ssi.species <- data.frame(species=dir(ssi.dir, pattern=".txt$"),in.PM=NA)

  ssi.data <- data.frame(species=NA,easting=NA,northing=NA)

  ignore.ssi <- ssi.species$species[gsub("_"," ",gsub("_GH.PM.txt","",ssi.species$species)) %in% me.species$species]
  if(length(ignore.ssi) > 0) ssi.species <- ssi.species[!grepl(paste0(ignore.ssi,collapse="|"),ssi.species),]

for(i in seq(ssi.species$species)){
  try({
    species.data <- read.table(paste0(ssi.dir,ssi.species$species[i]),sep="\t")
    colnames(species.data) <- c("easting","northing","V3","V4")
  species <- strsplit(as.character(ssi.species$species[i]),"_GH.PM.txt")
    species.data$species <- species  
    species <- gsub(" ","_",species)
    
    
  # identify points within region
    in.PM <- length(which(!is.na(extract(PM.clipping.mask,species.data[,c("easting","northing")]))))
    
    if(in.PM>0) {
      ssi.species$in.PM[i] <- "TRUE"
      cat(as.character(species),"has",in.PM,"points in PM","\n")
          
      presence.absence.raster(PM.clipping.mask,species.data[,1:2], raster.label=species)
      
      ssi.data <- rbind(ssi.data,species.data[,c("species","easting","northing")])
      
      species <- gsub("_"," ",species)
#       protected.species$PM.sdm[protected.species$Scientific.Name==as.character(species)] <- "SSI"
#       protected.species$lower.hunter[protected.species$Scientific.Name==as.character(species)] <- in.PM
    
    } else ssi.species$in.PM[i] <- "FALSE"
  })
  }

ssi.data$species <- as.character(ssi.data$species)
  ssi.data <- ssi.data[-1,]

write.csv(ssi.data, paste0(PM.zonation.dir,"output/other species point data in PMH LGA.csv"),row.names=F )
write.csv(ssi.species,paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/ssi.species.csv"),row.names=F)
write.csv(protected.species,paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"),row.names=F)

```


```{r check for rasters of the wrong dimensions}
cells <- length(PM.clipping.mask[!is.na(PM.clipping.mask)])

tifs <- dir(PM.zonation.dir, pattern=".PM.tif$",full.names=T)

errors <- NULL

steps <- length(tifs)
bar <- txtProgressBar(min=0,max=steps,style=3)

for(i in seq(tifs)){
  
  setTxtProgressBar(bar,i)
  
  r<- raster(tifs[i])
  # check if the same size
  if(length(r[!is.na(r)])!= cells) {
    r <- mask(crop(r,PM.clipping.mask),PM.clipping.mask)
    # if now the right size and still has data, save raster
    if(cellStats(r,max)>0 & length(r[!is.na(r)])== cells) {
      writeRaster(r,paste0(PM.zonation.dir,tifs[i]),overwrite=T)
    } else errors <- append(errors,tifs[i])
  }
}

close(bar)

# note that this is a hack as these files still aren't the same size - not sure why
#sewpac <- c("ghff_foraging_PM.tif","koala_rawhabval6_PM.tif","Regent_Honeyeater_PM.tif","Swift_Parrot_PM.tif")
#errors <- errors[!errors %in% sewpac]

## only run this if you definitely want to delete these files!!
# file.remove(paste0(PM.zonation.dir,errors))

```


```{r create zonation spp file}
PM.zonation.dir <- paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/") 

# list all tifs in directory
tifs <- dir(PM.zonation.dir, pattern=".tif$")

# identify threatened plants to be included
included.plants <- read.csv(paste0(PM.zonation.dir,"PMHC threatened plants to include.csv"))

# identify species to be excluded
PMHC.ignore <- read.csv(paste0(PM.zonation.dir,"output/PM_new.species.csv"))
  PMHC.ignore <- PMHC.ignore$species[PMHC.ignore$ignore=="Y"]
  PMHC.ignore <- as.character(append(as.character(PMHC.ignore),c("Eudyptula minor","Morus serrator",setdiff(protected.species$Scientific.Name[protected.species$Taxa=="plants"],included.plants$ScientificName),as.character(protected.species$Scientific.Name[protected.species$ignore=="Y"]))))
  PMHC.ignore <- unique(PMHC.ignore)


# remove species that are listed to ignore
  tifs <- tifs[!tifs %in% paste0(gsub(" ","_",PMHC.ignore),"_SDM.PM.tif")]
  tifs <- tifs[!tifs %in% paste0(gsub(" ","_",PMHC.ignore),"_SSI.PM.tif")]

duplicates <- tifs[duplicated(gsub("SDM.PM.tif|SSI.PM.tif","",tifs))]
  if(length(duplicates)>0) tifs <- tifs[!tifs %in% gsub("SDM","SSI",duplicates)]

#export.species <- c(as.character(me.species$species[me.species$in.PM==TRUE]),as.character(ssi.species$species[ssi.species$in.PM==TRUE]))

PM.zonation.spp <- data.frame(weight=rep(1.0,length(tifs)), alpha=1.0, bqp.row=1.0, bqp.buffer=1.0, cell.removal=1.0, species=NA )
  PM.zonation.spp$species <- tifs
    #PM.zonation.spp$species <- paste0(export.species,"_PM.tif")
    #PM.zonation.spp$species <- gsub(" ","_",PM.zonation.spp$species)
    #PM.zonation.spp$species <- gsub("_GH.txt","",PM.zonation.spp$species)

write.table(PM.zonation.spp,paste0(PM.zonation.dir,"PM.zonation.spp"),sep="\t",row.names=FALSE, col.names=FALSE)


# weighted spp file based on GH weights
weights <- protected.species[protected.species$ignore!="Y",c("Scientific.Name","weight")]
  weights <- weights[!is.na(weights$weight),]

#species weights
for(i in seq(PM.zonation.spp$species)){
  try(PM.zonation.spp$weight[i] <- weights$weight[weights$Scientific.Name == gsub("_"," ",gsub("\\.PM|\\.tif|\\_SDM|\\_SSI","",PM.zonation.spp$species[i]))],silent=T)
}
  PM.zonation.spp$weight[is.na(PM.zonation.spp$weight)] <- 1


write.table(PM.zonation.spp,paste0(PM.zonation.dir,"PM.zonation.weighted.spp"),sep="\t",row.names=FALSE, col.names=FALSE)


write.csv(protected.species,paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"),row.names=F)

```

```{r useful functions}
trim <- function (x) gsub("^\\s+|\\s+$", "", x)

strip.names <- function(x){
  trim(gsub("_"," ",gsub("\\.PM|\\.tif|_SSI|_SDM","",x)))
}


```

```{r create zonation spp file}
old.tifs <- dir(paste0(PM.zonation.dir,"original tifs/"), pattern=".tif$")

# remove species that are listed to ignore
  old.tifs <- old.tifs[!old.tifs %in% paste0(gsub(" ","_",protected.species$Scientific.Name[protected.species$ignore=="Y"]),"SDM.PM.tif")]
  old.tifs <- old.tifs[!old.tifs %in% paste0(gsub(" ","_",protected.species$Scientific.Name[protected.species$ignore=="Y"]),"SSI.PM.tif")]
  old.tifs <- old.tifs[!old.tifs %in% paste0(gsub(" ","_",PMHC.ignore),"_SDM.PM.tif")]
  old.tifs <- old.tifs[!old.tifs %in% paste0(gsub(" ","_",PMHC.ignore),"_SSI.PM.tif")]

duplicates <- old.tifs[duplicated(gsub("SDM.PM.tif|SSI.PM.tif","",old.tifs))]
  if(length(duplicates)>0) old.tifs <- old.tifs[!old.tifs %in% gsub("SDM","SSI",duplicates)]

new.sp <- setdiff(tifs,old.tifs)

new.sp <- data.frame(species=strip.names(setdiff(tifs,old.tifs)),common.name=NA,taxa=NA,family=NA,status=NA,datatype=NA,mnes=NA)

new.sp$common.name <- protected.species$Common.Name[protected.species$Scientific.Name %in% new.sp$species]
new.sp$taxa <- protected.species$Taxa[protected.species$Scientific.Name %in% new.sp$species]
new.sp$family <- protected.species$Family[protected.species$Scientific.Name %in% new.sp$species]
new.sp$status <- protected.species$combined.status[protected.species$Scientific.Name %in% new.sp$species]
new.sp$mnes <- protected.species$mnes[protected.species$Scientific.Name %in% new.sp$species]
new.sp$datatype[grepl("SDM",setdiff(tifs,old.tifs))] <- "SDM"
new.sp$datatype[grepl("SSI",setdiff(tifs,old.tifs))] <- "points"

write.csv(new.sp,paste0(PM.zonation.dir,"output/","PM_new.species.csv"),row.names=F)

```

```
