---
title: "Maxent summary for PM DotE report"
author: "Amy Whitehead"
date: "Friday, January 30, 2015"
output: html_document
---

```{r}
rm(list=ls())

library(dplyr)

# computer <- "~" #My computer
computer <- "Z:/Amy" #Super computer
# computer <- "//654cw-20990/Amy"

source("R code/rbind.columns.r")

# define paths for input and output files
maxent.dir <- paste0(computer,'/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/')
PM.zonation.dir <- paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/output/") 

taxa <- c("birds","mammals","plants","reptiles","amphibians")

protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))

PM.protected.sp <- protected.species$Scientific.Name[!is.na(protected.species$PM.sdm)]

PM.spp.file <- read.table(paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/PM.zonation.spp"),sep="\t")
#   PM.sp <- PM.sp[grepl("SDM",PM.sp[,6]),6]
  PM.spp.file <- PM.spp.file[,6]
PM.ssi <- PM.spp.file[grepl("SSI",PM.spp.file)]
  PM.spp.file <- gsub("_"," ",gsub("_SSI|_SDM|\\.PM.tif","",PM.spp.file))

 PM.sp <- unique(c(as.character(PM.protected.sp),PM.spp.file))

PM.plants <- read.csv(paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/PMHC threatened plants to include.csv"))

```

```{r functions}

se <- function(x){
  (sqrt(var(na.omit(x)))/(length(na.omit(x))))
}

```


```{r extract maxent results}
envi.parameters <- c("Taxa","Family","Species","Common.Name","Comm.Status","NSW.Status","MNES","GH.records","PM.records","Data.type","Training.samples","Test.AUC","AUC.Standard.Deviation","cold_temp","hot_temp","mean_rain","seasonal_rain","mean_solar","slope","rugg1000","terr1000","wetness","final_vegetation","2000Dry_sclerophyll_forests","2000Rainforests","2000Wet_sclerophyll_forests","soil")

for (i in seq(taxa)){
  if(taxa[i]=="birds"){
    maxentResults.CV <- read.csv(paste0(maxent.dir,taxa[i],"/pre1750v3_PMHC/CV/MaxentResults.csv"))
    maxentResults.Full <- read.csv(paste0(maxent.dir,taxa[i],"/pre1750v3_PMHC/Full/MaxentResults.csv"))
  } else {
    maxentResults.CV <- read.csv(paste0(maxent.dir,taxa[i],"/pre1750v2/CV/MaxentResults.csv"))
    maxentResults.Full <- read.csv(paste0(maxent.dir,taxa[i],"/pre1750v2/Full/MaxentResults.csv"))
  }

  maxentResults.CV <- maxentResults.CV[grepl("average",maxentResults.CV$Species),]
  parameters <- c("Species","X.Training.samples","Test.AUC","AUC.Standard.Deviation",names(maxentResults.Full[grepl("permutation.importance",names(maxentResults.Full))]))
  
  maxentResults.CV <- maxentResults.CV[,names(maxentResults.CV) %in% as.character(parameters[1:4])]
  
  maxentResults.Full <- maxentResults.Full[,names(maxentResults.Full) %in% as.character(parameters[c(5:14)])]
  
  maxentResults <- cbind(maxentResults.CV,maxentResults.Full)
  
  names(maxentResults) <- gsub("X\\.|X|.permutation.importance","",names(maxentResults))

maxentResults$Species <- gsub("_"," ",gsub(" \\(average\\)","",maxentResults$Species))
maxentResults <- maxentResults[maxentResults$Species %in% as.character(PM.sp),]
maxentResults <- maxentResults[order(maxentResults$Species),]
# maxentResults[,5:ncol(maxentResults)] <- round(maxentResults[,5:ncol(maxentResults)],2)
#  maxentResults$Test.AUC <- paste0(round(maxentResults$Test.AUC,3)," (",round(maxentResults$AUC.Standard.Deviation,3),")")
# maxentResults <- maxentResults[,!names(maxentResults) %in% "AUC.Standard.Deviation"]
maxentResults$Taxa <- taxa[i]
maxentResults$Family <- protected.species$Family[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$Common.Name <- protected.species$Common.Name[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$Comm.Status <- protected.species$Comm.status[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$NSW.Status <- protected.species$NSW.status[protected.species$Scientific.Name %in% maxentResults$Species]
# maxentResults$Status <- protected.species$combined.status[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$MNES <- protected.species$mnes[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$GH.records <- protected.species$greater.hunter[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$PM.records <- protected.species$PM[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$Data.type <- "SDM"
envi.order <- envi.parameters[envi.parameters %in% names(maxentResults)]  
maxentResults <- maxentResults[,envi.order]

assign(paste0(taxa[i],"_MR"),maxentResults)
 write.csv(maxentResults,paste0(PM.zonation.dir,taxa[i],"_PM report - maxent summary.csv"),row.names=F) 
}

plants_MR <- plants_MR[plants_MR$Species %in% sort(PM.plants$ScientificName),]

```

```{r get details of SSI species}

ssiResults <- as.data.frame(matrix(NA,length(PM.ssi),ncol(maxentResults)))
  names(ssiResults) <- names(maxentResults)

ssiResults$Species <- gsub("_"," ",gsub("_SSI.PM.tif","",PM.ssi))

  ssiResults$Taxa <- protected.species$Taxa[protected.species$Scientific.Name %in% ssiResults$Species]
  ssiResults$Family <- protected.species$Family[protected.species$Scientific.Name %in% ssiResults$Species]
  ssiResults$Comm.Status <- protected.species$Comm.status[protected.species$Scientific.Name %in% ssiResults$Species]
  ssiResults$NSW.Status <- protected.species$NSW.status[protected.species$Scientific.Name %in% ssiResults$Species]
  # ssiResults$Status <- protected.species$combined.status[protected.species$Scientific.Name %in% ssiResults$Species]
  ssiResults$MNES <- protected.species$mnes[protected.species$Scientific.Name %in% ssiResults$Species]
  ssiResults$GH.records <- protected.species$greater.hunter[protected.species$Scientific.Name %in% ssiResults$Species]
  ssiResults$PM.records <- protected.species$PM[protected.species$Scientific.Name %in% ssiResults$Species]
  ssiResults$Data.type <- "SSI"

```



```{r combine outputs}
output <- rbind.columns(birds_MR,mammals_MR)
  output <- rbind.columns(output,plants_MR)
  output <- rbind.columns(output,reptiles_MR)
  output <- rbind.columns(output,amphibians_MR)
  output <- rbind.columns(output,ssiResults)

output <- output[order(output$Species),]
envi.order <- envi.parameters[envi.parameters %in% names(output)] 
output <- output[,envi.order]

duplicated.sp <- paste0(output$Species[duplicated(output$Species)],collapse="|")
  output <- output[!(grepl(duplicated.sp,output$Species) & grepl("SSI",output$Data.type)),]
  output$Data.type[grepl(duplicated.sp,output$Species) & grepl("SDM",output$Data.type)] <- "SSI"

# remove species that shouldn't be included in summary
# sp.remove <- c("Lathamus discolor","Anthochaera phrygia","Chalcites osculans","Dicksonia antarctica","Eucalyptus oblonga","Isopogon dawsonii","Tregellasia capito")

# output <- output[!output$Species %in% sp.remove,] 

write.csv(output[output$Species %in% PM.spp.file,],paste0(PM.zonation.dir,"PM report - feature list.csv"),row.names=F)

poorly.modelled <- output[output$Test.AUC<0.7,c("Taxa","Species","Common.Name","Comm.Status","NSW.Status","MNES","GH.records","PM.records","Test.AUC","AUC.Standard.Deviation")]
write.csv(poorly.modelled,paste0(PM.zonation.dir,"PM report - poorly modelled species.csv"),row.names=F)
```

```{r mean summary table}
names(output) <- gsub("2000","",names(output))

summary <- {
  output %>%
    group_by(Taxa) %>%
      summarise(
        N = n(),
        AUC.mean = mean(Test.AUC, na.rm=T),
        AUC.se = se(Test.AUC),
        cold_temp.mean = mean(cold_temp, na.rm=T),
        cold_temp.se = se(cold_temp),
        hot_temp.mean = mean(hot_temp, na.rm=T),
        hot_temp.se = se(hot_temp),
        mean_rain.mean = mean(mean_rain, na.rm=T),
        mean_rain.se = se(mean_rain),
        seasonal_rain.mean = mean(seasonal_rain, na.rm=T),
        seasonal_rain.se = se(seasonal_rain),
        mean_solar.mean = mean(mean_solar),
        mean_solar.se = se(mean_solar),
        slope.mean = mean(slope, na.rm=T),
        slope.se = se(slope),
        rugg1000.mean = mean(rugg1000, na.rm=T),
        rugg1000.se = se(rugg1000),
        terr1000.mean = mean(terr1000, na.rm=T),
        terr1000.se = se(terr1000),
        final_vegetation.mean = mean(final_vegetation, na.rm=T),
        final_vegetation.se = se(final_vegetation),
        Dry_sclerophyll_forests.mean = mean(Dry_sclerophyll_forests, na.rm=T),
        Dry_sclerophyll_forests.se = se(Dry_sclerophyll_forests),
        Rainforests.mean = mean(Rainforests, na.rm=T),
        Rainforests.se = se(Rainforests),
        Wet_sclerophyll_forests.mean = mean(Wet_sclerophyll_forests, na.rm=T),
        Wet_sclerophyll_forests.se = se(Wet_sclerophyll_forests),
        soil.mean = mean(soil, na.rm=T),
        soil.se = se(soil)
        )
}

summary.table <- as.data.frame(summary)
  summary.table[,c("cold_temp.mean","cold_temp.se","hot_temp.mean","hot_temp.se","mean_rain.mean","mean_rain.se","seasonal_rain.mean","seasonal_rain.se","mean_solar.mean","mean_solar.se","slope.mean","slope.se","rugg1000.mean","rugg1000.se","terr1000.mean","terr1000.se","final_vegetation.mean","final_vegetation.se","Dry_sclerophyll_forests.mean","Dry_sclerophyll_forests.se","Rainforests.mean","Rainforests.se","Wet_sclerophyll_forests.mean","Wet_sclerophyll_forests.se","soil.mean","soil.se")] <- round(summary.table[,c("cold_temp.mean","cold_temp.se","hot_temp.mean","hot_temp.se","mean_rain.mean","mean_rain.se","seasonal_rain.mean","seasonal_rain.se","mean_solar.mean","mean_solar.se","slope.mean","slope.se","rugg1000.mean","rugg1000.se","terr1000.mean","terr1000.se","final_vegetation.mean","final_vegetation.se","Dry_sclerophyll_forests.mean","Dry_sclerophyll_forests.se","Rainforests.mean","Rainforests.se","Wet_sclerophyll_forests.mean","Wet_sclerophyll_forests.se","soil.mean","soil.se")],2)
  summary.table[,c("AUC.mean","AUC.se")] <- round(summary.table[,c("AUC.mean","AUC.se")],4)
  summary.table <- as.data.frame(t(summary.table[,2:ncol(summary.table)]))
  names(summary.table) <- c("amphibians","birds","mammals","plants","reptiles")
  summary.table <- summary.table[,c("amphibians","birds","mammals","plants","reptiles")]

envi.parameters <- gsub("2000|Test\\.","",envi.parameters)

for(i in seq(envi.parameters)){
  if(length(nrow(summary.table[grepl(envi.parameters[i],row.names(summary.table)),])==2)){
    test <- summary.table[grepl(envi.parameters[i],row.names(summary.table)),]
    for(k in 1:5){
      test[1,k] <- paste0(test[1,k]," (",test[2,k],")")
      test[1,k] <- gsub("NaN \\(NA\\)|NA \\(NA\\)","\\-",as.character(test[1,k]))
    }
  summary.table[row.names(summary.table)==paste0(envi.parameters[i],".mean"),] <- test[1,]
  rm(test)
  }
}

summary.table <- summary.table[!grepl("\\.se",row.names(summary.table)),]
row.names(summary.table) <- gsub("\\.mean","",row.names(summary.table))
  
write.csv(summary.table,paste0(PM.zonation.dir,"PM report - maxent parameter summary.csv"),row.names=T)

```


```{r plot AUC values}

output$Taxa <- factor(output$Taxa, levels=c("amphibians","birds","mammals","plants","reptiles"))

png(paste0(PM.zonation.dir,"PM.AUC_boxplot.png"),width=15,height=15,units = "cm",pointsize=12,bg="transparent",res=300)
par(las=1,mar=c(4,6,2,2))
boxplot(Test.AUC~Taxa, data=output, xlab="AUC",horizontal = T)
abline(v=0.7,lty=3)
dev.off()


```
