---
title: "PM_extract results & figures for report"
author: "Amy Whitehead"
date: "Wednesday, April 22, 2015"
output: html_document
---


```{r set up}
rm(list=ls())
library(raster)
library(maptools)
library(colorRamps)
library(fields)
library(RColorBrewer)
library(scales)

  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# computer
# computer <- "~"
#computer <- "//654cw-20990/Amy"
computer <- "Z:/Amy"
# computer <- "I:/Super Computer Data"

# define paths for input and output files
input_path <- paste0(computer,'/GIS_data/Hunter/zonation/port macquarie/')
output_path <- paste0(computer,'/GIS_data/Hunter/zonation/port macquarie/output/')

# import biodiversity feature names
  names <- as.vector(read.table(paste0(input_path,'PM.zonation.spp'), header=F, sep='\t')[,6])
  species <- gsub('\\.PM\\.tif|_SDM|_SSI', '', names)

# date of the output files
  analysis.date <- '20150424' # remember to update to correct date

 protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))
  protected.species <- protected.species[order(protected.species$Scientific.Name),]

guilds <- read.csv(paste0(output_path,"PMHC species of interest.csv"))
  guilds <- guilds[order(guilds$species),]

PM.mask <- raster(paste0(computer,"/GIS_Data/Hunter/mask files/PM.mask.tif"))
PM.clipping.mask <- raster(paste0(computer,"/GIS_Data/Hunter/mask files/PM.clipping.mask.tif"))
PM.shp <- readShapePoly(paste0(computer,"/GIS_data/Port Macquarie/Data from PMH/PMHC LGA boundary.shp"), proj4=GDA94.56)

GH_PM.shp <- readShapePoly(paste0(computer,"/GIS_data/Hunter/mask files/GH_PM.shp"), proj4=GDA94.56)
GH_PM.mask <- raster(paste0(computer,"/GIS_Data/Hunter/mask files/GH_PM.mask.tif"))
GH_PM.clipping.mask <- raster(paste0(computer,"/GIS_Data/Hunter/mask files/GH_PM.clipping.mask.tif"))

```

```{r colour palettes}
# define top fractions of interest
top.fraction <- c(0.05, 0.1, 0.15, 0.3)
pri.breaks <- sort(c(0,1-top.fraction,1))

# plotting
pri.col = c('dark grey', 'turquoise', 'yellow', 'orange', 'red')
pa.col = c('palegreen3', 'palegreen4')
map.background <- 'light grey'

pri.labels <- c("top 5%","top 10%","top 15%","top 30%","rest")
pa.labels <- c("High security","Low security")

```

```{r useful functions}
trim <- function (x) gsub("^\\s+|\\s+$", "", x)

strip.names <- function(x){
  trim(gsub("_"," ",gsub("\\.PM|\\.tif|_SSI|_SDM","",x)))
}

```

```{r remnant vegetation maps}

png(paste0(output_path,'PM_remnant veg.png'), width =21, height = 12, units="cm",res=300,bg="transparent",pointsize=12)
par(mfrow=c(1,2), mar=c(0,0,0,0), oma=c(0,0,0,0))
plot(GH_PM.clipping.mask,col="darkgreen",legend=F,box=F,axes=F,zlim=c(0,1000))
  plot(GH_PM.shp,add=T,border="grey20",lwd=1)
  plot(PM.shp,add=T,lwd=2)
  mtext("A",side=3,line=-2,font=2,adj=0)
  mtext("Greater Hunter & Port Macquarie - Hastings",side=3,line=-2,font=1,adj=0.15,cex=0.8)
  scalebar(50000,xy = c(197142,6282948),type = "line",label=c("50 km"),cex=0.75)

plot(PM.clipping.mask,col="darkgreen",axes=F,legend=F,box=F)
  plot(PM.shp,add=T)
  mtext("B",side=3,line=-2,font=2,adj=0)
  mtext("Port Macquarie - Hastings",side=3,line=-2,font=1,adj=0.15,cex=0.8)
  scalebar(10000,xy = c(411042.2,6488048),type = "line",label=c("10 km"),cex=0.75)
dev.off()

```

```{r import baseline curve data}
# PM General impact assessment

# get names of Zonation curves-files 
files <- grep(paste0(analysis.date,'.curves.txt'), list.files(input_path), value=T) 

  baseline.curves <- read.table(paste0(output_path,"output_PMbase_",analysis.date,".curves.txt"), skip=1, header=F, sep='')
    colnames(baseline.curves) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2', species)

# check for species that have zero observations at the start of the prioritisation
  zero.obs <- baseline.curves[1,8:ncol(baseline.curves)]
    names(zero.obs[which(zero.obs==0)])

# when does the first species go extinct in the baseline scenario?
  extinct <- baseline.curves[baseline.curves$min_prop_rem==0,][1,]
    cat("First species goes extinct at step",row.names(extinct), "with",extinct$Prop_landscape_lost*100, "% removed","\n")
   names(extinct[which(extinct==0)])
  
```

```{r produce baseline priority map}

base_pri <- raster(paste0(output_path,"output_PMbase_",analysis.date,".rank.compressed.tif"))

top30 <- base_pri
  top30[top30<0.7] <- NA

png(paste0(output_path,"PM_unweighted_zonation_priority_",analysis.date,".png"),height=12,width=15,units="cm",res=300, bg="transparent",pointsize=11)
par(mar=c(0,0.25,0,0), oma=c(0,0,0,0))
plot(PM.mask,col=map.background,legend=F,box=F,axes=F,zlim=c(1,7))
  plot(base_pri,col=pri.col,breaks=pri.breaks,add=T,legend=F)
  plot(PM.shp, add=T, lwd=0.5)

legend('bottom', inset=c(0,0), pri.labels, col=rev(pri.col), pch=15, bty="n", title="Conservation priority", cex=1, xpd=T,horiz=T)

dev.off()


```

```{r map current protection of top 30}
# load PA mask and calculate proportion of NPs and State Forests
PA.clipping.mask <- raster(paste0(input_path,"scenarios/ProtectedAreas_v3_clipped.tif"))
PA.mask <- raster(paste0(input_path,"scenarios/PM_ProtectedAreas_v3.tif"))

PA.protected.mask <- PA.mask
  PA.protected.mask[PA.protected.mask==1] <- 0

PA.all <- PA.protected.mask
  PA.all[!is.na(PA.all)] <- 1

PA.high.protected.mask <- PA.mask
  PA.high.protected.mask[PA.high.protected.mask!=3] <- 0
#   protected.areas.plot[protected.areas.plot!=0] <- 1

PA.high <- PA.high.protected.mask
  PA.high[!is.na(PA.high)] <- 1

PA.low <- PA.mask
  PA.low[PA.low!=2] <- NA
  PA.low[!is.na(PA.low)] <- 1

base_pri.protected <- mask(PA.protected.mask + base_pri,top30)
base_pri.high.protected <- mask(PA.high.protected.mask + base_pri,top30)

# current protected areas
png(paste0(output_path,"Protected_Areas.png"), width = 15, height = 12, units="cm",res=300,bg="transparent",pointsize=11)
  par(mfrow=c(1,1), mar=c(0,0,0,0), oma=c(0,0,0,0))
    plot(PM.clipping.mask, col=map.background, legend=F, axes=F, box=F)
    plot(PA.protected.mask, breaks = c(0,1,2,3), col=c(NA,pa.col), add=T, legend=F, box=F)
    plot(PM.shp,add=T)
  legend('bottom', inset=c(0,0), pa.labels, col=rev(pa.col), pch=15, bty="n", title="Protected Areas", cex=1, xpd=NA, horiz=T, title.adj=0)
dev.off()

png(paste0(output_path,"Protected_Priorities_",analysis.date,".png"),height=12,width=15,units="cm",res=300, bg="transparent",pointsize = 11)
    par(mfrow=c(1,1),mar=c(0,0,0,0), oma=c(0,0,0,5),xpd=NA)
leg.labels <- c("Top 5%","Top 10%","Top 15%","Top 30%","","Protected priorities", "Protected areas")  

  plot(PA.clipping.mask,col=c("whitesmoke","grey70"),breaks=c(0,1,3),legend=F,box=F,axes=F)
    plot(base_pri.protected,add=T,col=c(NA,pri.col[2:5],"grey50"),breaks=c(0,0.7,0.85,0.9,0.95,1,4),legend=F)
    plot(PM.shp, add=T, lwd=0.5)
legend("bottomright",inset=c(-0.30,0.1),xjust=1,leg.labels,col=c(rev(pri.col[2:5]),NA,"grey50","grey70"),pch=15,bty="n",title="Conservation priorities",cex=1,xpd=NA)
    dev.off()

png(paste0(output_path,"Protected_Priorities_High_",analysis.date,".png"),height=12,width=15,units="cm",res=300, bg="transparent",pointsize = 11)
    par(mfrow=c(1,1),mar=c(0,0,0,0), oma=c(0,0,0,5),xpd=NA)
leg.labels <- c("Top 5%","Top 10%","Top 15%","Top 30%","","Protected priorities", "Protected areas")  

  plot(PA.clipping.mask,col=c("whitesmoke","grey70"),breaks=c(0,1,3),legend=F,box=F,axes=F)
#     plot(PA.clipping.mask,col=c("whitesmoke","grey70"),add=T,legend=F,breaks=c(0,1,2,3))
    plot(base_pri.high.protected,add=T,col=c(NA,pri.col[2:5],"grey50"),breaks=c(0,0.7,0.85,0.9,0.95,1,4),legend=F)
    plot(PM.shp, add=T, lwd=0.5)
legend("bottomright",inset=c(-0.30,0.1),xjust=1,leg.labels,col=c(rev(pri.col[2:5]),NA,"grey50","grey70"),pch=15,bty="n",title="Conservation priorities",cex=1,xpd=NA)
    dev.off()

png(paste0(output_path,"Protected_Priorities_both",analysis.date,".png"),height=12,width=25,units="cm",res=300, bg="white",pointsize = 10)
    par(mfrow=c(1,2),mar=c(0,0,0,0), oma=c(0,0,0,6),xpd=NA)
leg.labels <- c("Top 5%","Top 10%","Top 15%","Top 30%","","Protected priorities", "Protected areas")  

  plot(PA.clipping.mask,col=c("whitesmoke","grey70"),breaks=c(0,1,3),legend=F,box=F,axes=F)
    plot(base_pri.protected,add=T,col=c(NA,pri.col[2:5],"grey50"),breaks=c(0,0.7,0.85,0.9,0.95,1,4),legend=F)
    plot(PM.shp, add=T, lwd=0.5)
  mtext("A",side=3,line=-2,font=2,adj=0)
  mtext("Priorities outside all protected areas",side=3,line=-3,font=1,adj=0,cex=0.8)

  plot(PA.clipping.mask,col=c("whitesmoke","grey70"),breaks=c(0,2,3),legend=F,box=F,axes=F)
    plot(base_pri.high.protected,add=T,col=c(NA,pri.col[2:5],"grey50"),breaks=c(0,0.7,0.85,0.9,0.95,1,4),legend=F)
    plot(PM.shp, add=T, lwd=0.5)
  mtext("B",side=3,line=-2,font=2,adj=0)
  mtext("Priorities outside high security protected areas",side=3,line=-3,font=1,adj=0,cex=0.8)
legend("right",inset=c(-0.30,0),xjust=1,leg.labels,col=c(rev(pri.col[2:5]),NA,"grey50","grey70"),pch=15,bty="n",title="Conservation priorities",cex=0.8,xpd=NA)
    dev.off()

```

```{r summary of current protected areas}

PA.summary <- data.frame(PA=c("High security","Low security","Total"),PMHC.area=NA,PMHC.prop=NA,RemVeg.area=NA,RemVeg.prop=NA,mask.value=c(3,2,NA))

for(i in 1:2){
  PA.summary$PMHC.area[i] <- freq(PA.mask)[PA.summary$mask.value[i],2]
  PA.summary$RemVeg.area[i] <- freq(PA.clipping.mask)[PA.summary$mask.value[i],2]
}

  PA.summary$PMHC.area[3] <- sum(freq(PA.mask)[2:3,2])
  PA.summary$RemVeg.area[3] <- sum(freq(PA.clipping.mask)[2:3,2])  
  PA.summary$PMHC.prop <- PA.summary$PMHC.area/sum(freq(PA.mask)[1:3,2])
  PA.summary$RemVeg.prop <- PA.summary$RemVeg.area/sum(freq(PA.clipping.mask)[1:3,2])

write.csv(PA.summary,paste0(output_path,"Protected_Area summary_",analysis.date,".csv"),row.names=F)

np <- PA.summary$RemVeg.prop[1]
sf <- PA.summary$RemVeg.prop[2]
```

```{r load PA curves data}
# load curves files of the solution and find the fractions that mark protected areas
curves.PA <- read.table(paste0(output_path,"output_PM_PA_",analysis.date,".curves.txt"), skip=1, header=F, sep='')
  colnames(curves.PA) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2', species)

curves.PA.High <- read.table(paste0(output_path,"output_PM_PA_High_",analysis.date,".curves.txt"), skip=1, header=F, sep='')
  colnames(curves.PA.High) <- c('Prop_landscape_lost', 'cost_needed_for_top_fraction', 'min_prop_rem', 'ave_prop_rem', 'W_prop_rem', 'ext-1', 'ext-2', species)

protected.fraction <- curves.PA$Prop_landscape_lost[which(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)))==min(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)))))]
np.fraction <- curves.PA$Prop_landscape_lost[which(abs(curves.PA$Prop_landscape_lost-(1-(np)))==min(abs(curves.PA$Prop_landscape_lost-(1-(np)))))]

```

The following data is based on the prioritisations that included the PA masks

```{r load PA priority rasters & generate breaks}

# All protected areas
PA_pri <- raster(paste0(output_path,"output_PM_PA_",analysis.date,".rank.compressed.tif"))

# breaks used to categorize cells
PA_pri.breaks <- sort(c(0, (protected.fraction-top.fraction), protected.fraction))
PA_breaks <- c(protected.fraction, np.fraction, 1)

# priority cells outside al protected areas
PA_pri.unprotected <- PA_pri
PA_pri.unprotected[which(PA_pri.unprotected[] > protected.fraction)] <- NA

# protected cells
PA_pri.protected <- PA_pri
PA_pri.protected[which(PA_pri.protected[] < protected.fraction)] <- NA

# high security protected areas only
PA.high_pri <- raster(paste0(output_path,"output_PM_PA_high_",analysis.date,".rank.compressed.tif"))

# breaks used to categorize cells
PA.high_pri.breaks <- sort(c(0,(np.fraction-top.fraction), np.fraction))
PA.high_breaks <- c(np.fraction, 1)

# unprotected cells
PA.high_pri.unprotected <- PA.high_pri
PA.high_pri.unprotected[which(PA.high_pri.unprotected[] > np.fraction)] <- NA

# protected cells
PA.high_pri.protected <- PA.high_pri
PA.high_pri.protected[which(PA.high_pri.protected[] < np.fraction)] <- NA

```


```{r maps of protected priorities & expansion priorities}
#expansion priorities
png(paste0(output_path,"Expansion_Priorities_High_",analysis.date,".png"), width = 15, height = 12, units="cm",res=300,bg="transparent",pointsize=11)
  par(mfrow=c(1,1), mar=c(0,0,0,0), oma=c(0,0,0,0))
  plot(PM.clipping.mask, col=map.background, legend=F, axes=F, box=F)
    plot(PA.high_pri, breaks = unique(c(PA.high_pri.breaks,PA.high_breaks)), col=c(pri.col,pa.col[2]), add=T, legend=F,box=F)
    plot(PM.shp,add=T)
  legend('bottom', inset=c(0,0), pri.labels, col=rev(pri.col), pch=15, bty="n", title="Expansion priority", cex=1,xpd=NA, horiz=T, title.adj=0)
dev.off()

#Low security PAs
 PA.high_low.security <- PA.high_pri * PA.low

# Unprotected Crown & Council land
unprotected.crown.council <- raster(paste0(input_path,"scenarios/Unprotected_Crown_Council_protected_land.tif"))
  unprotected.crown.council[unprotected.crown.council==0] <- NA
  unprotected.crown.council[!is.na(unprotected.crown.council)] <- 1
PA.high_ccl <- PA.high_pri * unprotected.crown.council

#Private Native forests
pnf <- raster(paste0(input_path,"scenarios/Private_Native_Forests.tif"))
  pnf[pnf==0] <- NA
  pnf[!is.na(pnf)] <- 1
PA.high_pnf <- PA.high_pri * pnf


png(paste0(output_path,"Expansion_Priorities_within Low security_",analysis.date,".png"), width = 12, height = 25, units="cm",res=300,bg="transparent",pointsize=11)

par(mfrow=c(3,1), mar=c(0,0,2,0), oma=c(4,0,1,0))
plot(PM.clipping.mask, col=map.background, legend=F, axes=F, box=F)
  plot(PA.high_low.security, breaks = unique(c(PA.high_pri.breaks,PA.high_breaks)), col=c(pri.col,pa.col[2]), add=T, legend=F, box=F)
  plot(PM.shp,add=T)
  mtext("A",side=3,line=1,font=2,adj=0)
  mtext("Low security Protected Areas",side=3,line=0,font=1,adj=0,cex=0.8)

plot(PM.clipping.mask, col=map.background, legend=F, axes=F, box=F)
  plot(PA.high_ccl, breaks = unique(c(PA.high_pri.breaks,PA.high_breaks)), col=c(pri.col,pa.col[2]), add=T, legend=F, box=F)
  plot(PM.shp,add=T)
  mtext("B",side=3,line=1,font=2,adj=0)
  mtext("Unprotected Crown & Council Lands",side=3,line=0,font=1,adj=0,cex=0.8)

plot(PM.clipping.mask, col=map.background, legend=F, axes=F, box=F)
  plot(PA.high_pnf, breaks = unique(c(PA.high_pri.breaks,PA.high_breaks)), col=c(pri.col,pa.col[2]), add=T, legend=F, box=F)
  plot(PM.shp,add=T)
  mtext("C",side=3,line=1,font=2,adj=0)
  mtext("Private Native Forests",side=3,line=0,font=1,adj=0,cex=0.8)

legend('bottom', inset=c(0,-0.1), pri.labels, col=rev(pri.col), pch=15, bty="n", title="Expansion priority", cex=1.25, xpd=NA, horiz=T, title.adj=0)

dev.off()


```


```{r plot distribution size vs % in top priority}
sdm.species <- names[grepl("SDM",names)]

distribution.size <- read.table(paste0(output_path,"output_PMbase_",analysis.date,".features_info.txt"),skip=1,header=T)

distribution.size$relative.distribution <- distribution.size$distribution.sum
  distribution.size$relative.distribution[distribution.size$MapFileName %in% sdm.species] <- distribution.size$relative.distribution[distribution.size$MapFileName %in% sdm.species]/1000
  distribution.size$relative.distribution <- distribution.size$relative.distribution/272283
  distribution.size$top.30 <- t(baseline.curves[baseline.curves$Prop_landscape_lost>=(1-0.3),][1,8:ncol(baseline.curves)])

write.csv(distribution.size,paste0(output_path,"PM_distribution.size_",analysis.date,".csv"), row.names=F)


svg(paste0(output_path,"distribution.size_top30priority_",analysis.date,".svg"),height=6,width=6, bg="transparent",pointsize = 12)
# png(paste0(output_path,"distribution.size_top30priority.png"),height=15,width=15,units="cm",res=300, bg="transparent",pointsize = 12)
  par(mfrow=c(1,1),xpd=NA,las=1)

  plot(distribution.size$relative.distribution,distribution.size$top.30,ylim=c(0,1),xlim=c(0,0.6),xlab="Relative size of distribution",ylab="Proportion of distribution in top priorities",bty="l")

dev.off()

```


```{r create results table}

results <- data.frame(species=gsub("_"," ",species),common.name=NA,taxa=NA,family=NA,guild=NA,Comm.status=NA,NSW.status=NA,datatype=NA,mnes=NA,weight=NA,top5=NA,top10=NA,top15=NA,top30=NA)

results$top5 <- as.vector(t(baseline.curves[baseline.curves$Prop_landscape_lost>=0.95,][1,8:ncol(baseline.curves)]))
results$top10 <- as.vector(t(baseline.curves[baseline.curves$Prop_landscape_lost>=0.90,][1,8:ncol(baseline.curves)]))
results$top15 <- as.vector(t(baseline.curves[baseline.curves$Prop_landscape_lost>=0.85,][1,8:ncol(baseline.curves)]))
results$top30 <- as.vector(t(baseline.curves[baseline.curves$Prop_landscape_lost>=0.70,][1,8:ncol(baseline.curves)]))

results$common.name <- protected.species$Common.Name[protected.species$Scientific.Name %in% results$species]
results$taxa <- protected.species$Taxa[protected.species$Scientific.Name %in% results$species]
results$family <- protected.species$Family[protected.species$Scientific.Name %in% results$species]
results$NSW.status <- protected.species$NSW.status[protected.species$Scientific.Name %in% results$species]
results$Comm.status <- protected.species$Comm.status[protected.species$Scientific.Name %in% results$species]
results$mnes <- protected.species$mnes[protected.species$Scientific.Name %in% results$species]
  results$mnes[results$mnes=="FALSE"] <- ""
results$datatype[grepl("SDM",names)] <- "SDM"
results$datatype[grepl("SSI",names)] <- "points"
results$weight <- protected.species$weight[protected.species$Scientific.Name %in% results$species]
results$GH.points <- protected.species$greater.hunter[protected.species$Scientific.Name %in% results$species]
results$PM.points <- protected.species$PM[protected.species$Scientific.Name %in% results$species]
results$distribution.size <- round(distribution.size$relative.distribution*100,1)

for(s in seq(guilds$species)){
  results$guild[as.character(results$species) == as.character(guilds$species[s])] <- as.character(guilds$guild[s])
}
  results$guild[results$guild==""] <- NA

results <- results[,c("taxa","family","species","common.name","guild","NSW.status","Comm.status","mnes","datatype","distribution.size","GH.points","PM.points","top5","top10","top15","top30")]

```

```{r add protected priorities & expansion priorities to results table}

#species-specific protection within high security sites
results$PA.High <- as.vector(t(curves.PA[which(abs(curves.PA$Prop_landscape_lost-(1-np))==min(abs(curves.PA$Prop_landscape_lost-(1-np)))),8:ncol(curves.PA)]))
results$PA.Low <- NA
results$PA.Total <- as.vector(t(curves.PA[which(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)))==min(abs(curves.PA$Prop_landscape_lost-(1-(np+sf))))),8:ncol(curves.PA)]))
results$PA.Low <- results$PA.Total - results$PA.High

# expansion priorities based on High security only
results$expand.High5 <- as.vector(t(curves.PA.High[which(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.05))==min(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.05)))),8:ncol(curves.PA.High)]))
results$expand.High10 <- as.vector(t(curves.PA.High[which(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.10))==min(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.10)))),8:ncol(curves.PA.High)]))
results$expand.High15 <- as.vector(t(curves.PA.High[which(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.15))==min(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.15)))),8:ncol(curves.PA.High)]))
results$expand.High30 <- as.vector(t(curves.PA.High[which(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.3))==min(abs(curves.PA.High$Prop_landscape_lost-(1-np-0.30)))),8:ncol(curves.PA.High)]))

# expansion priorities based on all PAs
results$expand5 <- as.vector(t(curves.PA[which(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.05))==min(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.05)))),8:ncol(curves.PA)]))
results$expand10 <- as.vector(t(curves.PA[which(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.10))==min(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.10)))),8:ncol(curves.PA)]))
results$expand15 <- as.vector(t(curves.PA[which(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.15))==min(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.15)))),8:ncol(curves.PA)]))
results$expand30 <- as.vector(t(curves.PA[which(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.3))==min(abs(curves.PA$Prop_landscape_lost-(1-(np+sf)-0.30)))),8:ncol(curves.PA)]))

write.csv(results,paste0(output_path,"species-specific_results_",analysis.date,".csv"),row.names=F)

# identify the level of protection of the top priorities
protected.priorities <- data.frame(fraction = top.fraction, area=NA,PA.High=NA,PA.Low=NA,PA.Total=NA,No.PA=NA)

for(i in seq(top.fraction)){
  r <- top30
    r[r<(1-top.fraction[i])] <- NA
  protected.priorities$area[i] <- ncell(r[!is.na(r)])
  protected.priorities$PA.High[i] <- cellStats(!is.na(r * PA.high),sum)/protected.priorities$area[i]
  protected.priorities$PA.Low[i] <- cellStats(!is.na(r * PA.low),sum)/protected.priorities$area[i]
  protected.priorities$PA.Total[i] <- cellStats(!is.na(r * PA.protected.mask),sum)/protected.priorities$area[i]
  protected.priorities$No.PA[i] <- 1- protected.priorities$PA.Total[i] 
  rm(r)
}

write.csv(protected.priorities,paste0(output_path,"protected_summary_",analysis.date,".csv"),row.names=F)

```

```{r summary of top 30 results}

results.summary <- data.frame(scenario=c(names(results)[13:ncol(results)]),max.zonation=NA,mean.zonation=NA,min.zonation=NA,n.sp=NA,gap.sp=NA)

for(i in seq(results.summary$scenario)){
  scenario <- as.character(results.summary$scenario[i])
  results.summary$max.zonation[i] <- max(results[,scenario])
  results.summary$mean.zonation[i] <- mean(results[,scenario])
  results.summary$min.zonation[i] <- min(results[,scenario])
  results.summary$n.sp[i] <- length(which(results[,scenario]>0))
  results.summary$gap.sp[i] <- length(which(results[,scenario]==0))
}  

write.csv(results.summary,paste0(output_path,"PM_results.summary_",analysis.date,".csv"),row.names=F)


```


```{r boxplots of species in top 30, protection & expansion}

png(paste0(output_path,"PM_boxplot of distribution in top 30_",analysis.date,".png"),width=15,height=10,units="cm",bg="transparent",pointsize=10,res=300)
par(las=1,mar=c(4,6,1,1),oma=c(0,0,0,0))
boxplot(results$top30[results$mnes==TRUE],results$top30[results$mnes==""],names=c("MNES","non-MNES"),xlab="Proportion of distribution in top 30%",ylim=c(0,1),horizontal=T,col="lightgrey")
dev.off()

# tiff('species protection.tif', width = 15, height = 10, units="cm",res=300, compression='lzw', bg="transparent",pointsize=10)
png(paste0(output_path,"current species protection_",analysis.date,".png"), width = 15, height = 10, units="cm",res=300,bg="transparent",pointsize=10)
  
  par(las=1,mfrow=c(1,1), mar=c(4,9,1,1), oma=c(0,0,0,0))
  boxplot(results$PA.Total,results$PA.Low,results$PA.High,horizontal=T,xlab="Proportion of feature distributions protected",names=c("All protected areas","Low security","High security"),col=c("green4",pa.col),ylim=c(0,1))

dev.off()

png(paste0(output_path,"species protection with expansion_",analysis.date,".png"), width = 15, height = 10, units="cm",res=300,bg="transparent",pointsize=10)
  
  par(las=1,mfrow=c(1,1), mar=c(4,9,1,1), oma=c(0,0,0,0))
  boxplot(results$expand30,results$expand15,results$expand10,results$expand5,results$PA.High,horizontal=T,xlab="Proportion of feature distributions protected",names=c("Top 30% added","Top 15% added","Top 10% added","Top 5% added","High security"),col=c("lightgrey","lightgrey","lightgrey","lightgrey",pa.col[2]),ylim=c(0,1))

dev.off()

```

```{r guild summary}
guild.summary <- data.frame(guild=c(sort(unique(results$guild)[-1]),"All"),max.zonation=NA,mean.zonation=NA,min.zonation=NA,n.sp=NA,gap.sp=NA, sdm.sp=NA, pt.sp=NA)

for(i in 1:(nrow(guild.summary)-1)){
  guild <- as.character(guild.summary$guild[i])
  
  guild.summary$max.zonation[i] <- max(results[grepl(guild,results$guild),"top30"])
  guild.summary$mean.zonation[i] <- mean(results[grepl(guild,results$guild),"top30"])
  guild.summary$min.zonation[i] <- min(results[grepl(guild,results$guild),"top30"])
  guild.summary$n.sp[i] <- length(which(results[grepl(guild,results$guild),"top30"]>0))
  guild.summary$gap.sp[i] <- length(which(results[grepl(guild,results$guild),"top30"]==0))
  guild.summary$sdm.sp[i] <- nrow(results[(grepl(guild,results$guild) & grepl("SDM",results$datatype)),])
  guild.summary$pt.sp[i] <- nrow(results[(grepl(guild,results$guild) & grepl("points",results$datatype)),])
}  

  guild.summary$max.zonation[8] <- max(results[!is.na(results$guild),"top30"])
  guild.summary$mean.zonation[8] <- mean(results[!is.na(results$guild),"top30"])
  guild.summary$min.zonation[8] <- min(results[!is.na(results$guild),"top30"])
  guild.summary$n.sp[8] <- length(which(results[!is.na(results$guild),"top30"]>0))
  guild.summary$gap.sp[8] <- length(which(results[!is.na(results$guild),"top30"]==0))

write.csv(guild.summary,paste0(output_path,"PM_guild.summary_",analysis.date,".csv"),row.names=F)

```


```{r boxplots of guild top 30, protection & expansion}

png(paste0(output_path,"PM_boxplot of guild distributions in top 30_",analysis.date,".png"),width=15,height=15,units="cm",bg="transparent",pointsize=10,res=300)
par(mar=c(4,11,2,1),las=1)

boxplot(results$top30~results$guild,xlab="Proportion of distribution in top 30%",names=c("Amphibians",paste0("Cave-roosting","\n","microbats"),"Frugivorous birds","Nectarivorous birds",paste0("Phalangers, Phascogales","\n","& their predators"),"Shore birds","Water birds"),horizontal = T, ylim=c(0,1), col="lightgrey")
dev.off()

# tiff('species protection.tif', width = 15, height = 10, units="cm",res=300, compression='lzw', bg="transparent",pointsize=10)
png(paste0(output_path,"current guild protection",analysis.date,".png"),width=15,height=10,units="cm",bg="transparent",pointsize=10,res=300)
par(mar=c(4,11,2,1),las=1,oma=c(0,0,0,0))

boxplot(results$PA.High~results$guild,xlab="Proportion of distributions protected",names=c("Amphibians",paste0("Cave-roosting","\n","microbats"),"Frugivorous birds","Nectarivorous birds",paste0("Phalangers, Phascogales","\n","& their predators"),"Shore birds","Water birds"),horizontal = T,col="lightgrey")
dev.off()

png(paste0(output_path,"guild protection with expansion_",analysis.date,".png"), width = 15, height = 10, units="cm",res=300,bg="transparent",pointsize=10)
  
  par(mar=c(4,11,2,1),las=1,oma=c(0,0,0,0))

boxplot(results$expand30~results$guild,xlab="Proportion of distributions protected",names=c("Amphibians",paste0("Cave-roosting","\n","microbats"),"Frugivorous birds","Nectarivorous birds",paste0("Phalangers, Phascogales","\n","& their predators"),"Shore birds","Water birds"),horizontal = T,col="lightgrey")

dev.off()


```

```{r identify biodiversity features in runs}

input.summary <- data.frame(n.sp = NA,mnes.sp=NA,birds=NA,plants=NA,amphibians=NA,mammals=NA,reptiles=NA,sdm=NA,points=NA)

input.summary$n.sp <- length(species)
input.summary$mnes.sp <- length(results$species[grepl(TRUE,results$mnes)])
input.summary$birds <- length(results$species[grepl("birds",results$taxa)])
input.summary$plants <- length(results$species[grepl("plants",results$taxa)])
input.summary$mammals <- length(results$species[grepl("mammals",results$taxa)])
input.summary$amphibians <- length(results$species[grepl("amphibians",results$taxa)])
input.summary$reptiles <- length(results$species[grepl("reptiles",results$taxa)])
input.summary$sdm <- length(results$species[grepl("SDM",results$datatype)])
input.summary$points <- length(results$species[grepl("points",results$datatype)])

write.csv(input.summary,paste0(output_path,"PM_summary of input data_",analysis.date,".csv"),row.names=F)
```

See also "Hunter - talk images.r"

```{r plot map backgrounds for schematic diagram}

png(paste0(output_path,'PM_boundary.png'), width = 11, height = 10, units="cm",res=300,bg="transparent",pointsize=12)
par(mfrow=c(1,1), mar=c(0,0,0,0), oma=c(0,0,0,0))
plot(PM.mask, col="white", legend=F, axes=F, box=F)
  plot(PM.shp,add=T)
dev.off()

Aegotheles_cristatus_GH_PM <- raster(paste0(computer,"/GIS_data/Hunter/zonation/GH_PM/extant/Aegotheles_cristatus_SDM.GH_PM.tif"))
Aegotheles_cristatus_PM <- raster(paste0(computer,"/GIS_data/Hunter/zonation/port macquarie/Aegotheles_cristatus_SDM.PM.tif"))
all.points <- read.csv(paste0(computer,"/GIS_data/Hunter/Maxent_files/ghm.pm/species_data/maxent.data_birds.csv"))
sp.points <- all.points[grepl("Aegotheles cristatus",all.points$species),2:3]
coordinates(sp.points) <- c("x","y")
coordinates(sp.points) <- c("easting","northing")
sp.points.GH <- sp.points[!is.na(extract(Aegotheles_cristatus_GH_PM,sp.points)),]
sp.points.PM <- sp.points[!is.na(extract(Aegotheles_cristatus_PM,sp.points)),]

ssi.points <- read.table(paste0(computer,"/GIS_data/Hunter/zonation/greater hunter/ssi_files/Parsonsia dorrigoensis_GH.txt"))
coordinates(ssi.points) <- c("V1","V2")
  ssi.points.PM <- ssi.points[!is.na(extract(Aegotheles_cristatus_PM,ssi.points)),]

png(paste0(output_path,'PM_SDM.png'), width = 11, height = 10, units="cm",res=300,bg="transparent",pointsize=12)
par(mfrow=c(1,1), mar=c(0,0,0,0), oma=c(0,0,0,0))
plot(Aegotheles_cristatus_PM,col=blue2red(10),legend=F,box=F,axes=F,zlim=c(0,1000))
# points(sp.points.PM,pch=1,cex=0.5,col=alpha("black",0.5))
plot(PM.shp,add=T)
dev.off()

tiff(paste0(output_path,'PM_sdm_v2.tif'), width = 15, height = 25, units="cm",res=300, compression='lzw', bg="transparent",pointsize=12)
  par(mfrow=c(3,1),mar=c(1,1,3,1), oma=c(0,0,0,0),xpd=NA)
  plot(Aegotheles_cristatus_GH_PM,col=blue2red(10),legend=F,box=F,axes=F,zlim=c(0,1000))
    points(sp.points.GH,pch=1,cex=0.5,col=alpha("black",0.5))
    plot(GH_PM.shp,add=T,border="black",lwd=0.5)
    plot(PM.shp,add=T)
  mtext("A",side=3,line=0,font=2,adj=0)
  mtext("Australian owlet-nightjar",side=3,line=0,font=1,adj=0.15,cex=0.8)
  scalebar(50000,xy = c(197142,6282948),type = "line",label=c("50 km"),cex=0.75)

  plot(Aegotheles_cristatus_PM,col=blue2red(10),legend=F,box=F,axes=F,zlim=c(0,1000))
    points(sp.points.PM,pch=1,cex=0.5,col=alpha("black",0.5))
    plot(PM.shp,add=T)
  mtext("B",side=3,line=0,font=2,adj=0)
  mtext("Australian owlet-nightjar",side=3,line=0,font=1,adj=0.15,cex=0.8)

  image.plot(Aegotheles_cristatus_PM,small.plot=c(0,1,0,1),col=blue2red(10),legend.only=T,zlim=c(0,1000),axis.args = list(labels=c("Low","High"),at=c(0,1000),cex.axis=0.6),legend.args=list(text=paste0('Relative likelihood','\n','of occurrence'), side=3, font=2, line=2.5, cex=0.8),legend.shrink = 0.45)

  plot(PM.clipping.mask, col=map.background, legend=F, axes=F, box=F)
    plot(PM.shp,add=T)
    points(ssi.points.PM,pch=21,cex=0.5,col="black",bg="darkgreen")
  mtext("C",side=3,line=0,font=2,adj=0)
  mtext("Milky silkpod",side=3,line=0,font=1,adj=0.15,cex=0.8)
  scalebar(10000,xy = c(332142.2,6303031),type = "line",label=c("10 km"),cex=0.75)

dev.off()

tiff('PM_remnant veg.tif', width = 20, height = 10, units="cm", compression='lzw', res=300,bg="transparent",pointsize=12)
  par(mfrow=c(1,2), mar=c(1,1,1,1), oma=c(0,0,0,0))
  plot(GH_PM.clipping.mask,col="darkgreen",legend=F,box=F,axes=F,zlim=c(0,1000))
    plot(GH_PM.shp,add=T,border="grey20",lwd=1)
    plot(PM.shp,add=T,lwd=2)
    mtext("A",side=3,line=0,font=2,adj=0)
    mtext("Greater Hunter",side=3,line=0,font=1,adj=0.15,cex=0.8)
    scalebar(50000,xy = c(197142,6282948),type = "line",label=c("50 km"),cex=0.75)
  
  plot(PM.mask,col=map.background,axes=F,legend=F,box=F)
    plot(PM.clipping.mask,col="darkgreen",add=T,legend=F)
    plot(PM.shp,add=T)
    mtext("B",side=3,line=0,font=2,adj=0)
    mtext("Port MacQuarie-Hastings",side=3,line=0,font=1,adj=0.15,cex=0.8)
    scalebar(10000,xy = c(332142.2,6303031),type = "line",label=c("10 km"),cex=0.75)
dev.off()

```


Map showing how the vegetation layer was compiled at the GHPM scalue
```{r composite vegetation map}
GH.veg <- raster(paste0(computer,"/GIS_data/Hunter/mask files/GH.clipping.mask.tif"))
LH.veg <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.clipping.mask.tif"))
PM.veg <- mask(raster(paste0(computer,"/GIS_data/Port MacQuarie/Data from PMH/portveg2406_2013.tif")),PM.clipping.mask)
Crafti.veg <- mask(raster(paste0(computer,"/GIS_data/Port MacQuarie/Data from PMH/CRAFTI_veg_mapping.tif")),PM.clipping.mask)

GH.veg[!is.na(GH.veg)] <- 1
LH.veg[!is.na(LH.veg)] <- 2
PM.veg[!is.na(PM.veg)] <- 4
Crafti.veg[!is.na(Crafti.veg)] <- 3

composite.veg <- mask(merge(PM.veg,Crafti.veg,LH.veg,GH.veg),GH_PM.mask)

veg.colour <- brewer.pal(4,"Paired")
veg.labels <- c("PM Veg","CRAFTI Veg","LH Veg","GHMv4")

png(paste0(output_path,"composite_vegetation.png"),height=12,width=15,units="cm",res=300,bg="transparent",pointsize=10)
  par(mar=c(0,0,0,0),oma=c(0,0,0,0))
  plot(GH_PM.mask,col=map.background,axes=F,box=F,legend=F)
  plot(composite.veg, col=veg.colour,axes=F, legend=F, add=T)
  plot(GH_PM.shp,add=T)
  legend("bottomright",inset=c(-0.10,0.2),xjust=1,veg.labels,col=rev(veg.colour),pch=15,bty="n",title="Vegetation datasets",cex=1,xpd=NA)
dev.off()

```

