---
title: "Clip TEC models by bioregion"
author: "Amy Whitehead"
date: "Thursday, July 03, 2014"
output: html_document
---

Clip the final MaxEnt outputs for the TECs by the appropriate bioregions listed in the TEC names
Clip the SSI points by IBRA regions

```{r setup}
rm(list=ls())

packages(maptools)
packages(rgdal)
packages(raster)
source("C:/Users/awhitehead/Dropbox/Random R code/shp2raster.R")
 computer <- "//654cw-20990/Amy"
# computer <- "Z:/Amy"

# projections
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs")
  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +units=m +no_defs")

# load TEC descriptions
  TEC.data <- read.csv("~/GIS_data/Hunter/All data from harddrive/From HCCREMS/TEC_data/GreaterHunter_DRAFT_100812 (2).csv")

# load GH.PM boundary
  gh.pm <- readShapePoly("~/GIS_Data/Hunter/mask files/GH_PM.shp",proj4string=GDA94.56)
  gh.pm.clipping.mask <- raster(paste0(computer,"/GIS_Data/Hunter/mask files/GH_PM.clipping.mask.tif"),proj4string=GDA94.56)
    gh.pm.clipping.mask[!is.na(gh.pm.clipping.mask)] <- 0

# load IBRA regions
  ibra <- readShapePoly("~/GIS_data/Australia-wide/IBRA7_subregions/IBRA7_subregions.shp",proj4string=GDA94)
    ibra <- spTransform(ibra,GDA94.56)
    ibra <- ibra[grepl("Brigalow Belt South|Sydney Basin|South East Corner|New England Tablelands|NSW North Coast",ibra$REG_NAME_7),]
    ibra <- crop(ibra,gh.pm)
  bioregions <- c("Brigalow Belt South","Sydney Basin","South East Corner","New England Tablelands","NSW North Coast")

```

```{r import rasters and mask by bioregion}

  tecs <- stack(dir("//654cw-20990/Amy/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/tecs/BRT/",pattern=".tif$",full.names=T))

for(i in 1:nlayers(tecs)){
  r <- tecs[[i]]
  tec <- gsub("_avg","",names(r))
  # identify the bioregions in the tec name 
  regions <- bioregions[sapply(bioregions,grepl,gsub("_"," ",tec),ignore.case=T)]
  
  if(length(regions)>0){
    r <- merge(mask(r,ibra[grepl(paste(regions,collapse="|"),ibra$REG_NAME_7,ignore.case=T),]),gh.pm.clipping.mask)
    names(r) <- tec
  }
  
  #plot(r,axes=F,main=gsub("_"," ",tec),zlim=c(0,1000),box=F)
    
  writeRaster(r,filename=paste0("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/extant/",tec,"SDM_GH.tif"),overwrite=T,format="GTiff")
  assign(tec,r)
  cat(tec,"\n")
  suppressWarnings(rm(r,tec,regions))
}

setwd("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/extant/")
tifs <- dir("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/extant/",pattern="X\\_")
file.rename(tifs,gsub("X_","",tifs))
file.remove(tifs)
```


```{r import pre1750 rasters and mask by bioregion}

  tecs <- stack(dir("//654cw-20990/Amy/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/tecs/BRT/pre1750/",pattern=".tif$",full.names=T))

for(i in 1:nlayers(tecs)){
  r <- tecs[[i]]
  tec <- gsub("_avg","",names(r))
  # identify the bioregions in the tec name 
  regions <- bioregions[sapply(bioregions,grepl,gsub("_"," ",tec),ignore.case=T)]
  
  if(length(regions)>0){
    r <- merge(mask(r,ibra[grepl(paste(regions,collapse="|"),ibra$REG_NAME_7,ignore.case=T),]),gh.pm.clipping.mask)
    names(r) <- tec
  }
  
#   plot(r,axes=F,main=gsub("_"," ",tec),zlim=c(0,1000),box=F)
    
  writeRaster(r,filename=paste0("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/pre1750/",tec,"_pre1750_GH.tif"),overwrite=T,format="GTiff")
#   assign(tec,r)
  cat(tec,"\n")
  suppressWarnings(rm(r,tec,regions))
}

setwd("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/pre1750/")
tifs <- dir("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/pre1750/",pattern="X\\_")
file.rename(tifs,gsub("X_","",tifs))
file.remove(tifs)

```


```{r clip ssi tecs}

ssi <- dir("~/GIS_data/Hunter/zonation/greater hunter/ssi_files/",pattern="_GH.txt")

for(i in seq(ssi)){
  r <- read.table(paste0("~/GIS_data/Hunter/zonation/greater hunter/ssi_files/",ssi[i]))
  coordinates(r) <- r[,1:2]
  proj4string(r) <- GDA94.56
  # identify the bioregions in the tec name 
  regions <- bioregions[sapply(bioregions,grepl,gsub("_"," ",ssi[i]),ignore.case=T)]
  
  if(length(regions)>0){
    r.ibra <- ibra[grepl(paste(regions,collapse="|"),ibra$REG_NAME_7,ignore.case=T),]
    r <- r[r.ibra,]
    r <- as.data.frame(r)
    
    write.table(r[,3:6],file=paste0("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/ssi_files/",ssi[i]),row.names=FALSE, sep="\t", col.names=FALSE)  
    cat(ssi[i],"has",nrow(r),"records","\n")
  }
  suppressWarnings(rm(r,regions,r.ibra))
}

```
