Extract HCCREMS TEC data from GHM
========================================================



```{r import data}
  rm(list=ls())
  
  packages(maptools)
  packages(raster)

  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

  output.directory <- "~/GIS_data/Hunter/vegetation/GHM_MUcodes/"

# import HCCREMS spreadsheet with MU codes of TECs
  TEC.data <- read.csv("~/GIS_data/Hunter/All data from harddrive/From HCCREMS/TEC_data/GreaterHunter_DRAFT_100812 (2).csv")

# import GHM_v4 survey points
  ghm.survey <- readShapePoints("~/GIS_data/Hunter/vegetation/GHM_v4/GHM_v4_Surveus_June2012",proj4string=GDA94.56)

# import GHM_v4 polygon data
  ghm <- readShapePoly("~/GIS_data/Hunter/vegetation/GHM_MUcodes/GHM_TECS",proj4string=GDA94.56)

# import PB veg data
  pb <- readShapePoly("~/GIS_data/Hunter/vegetation/GHM_MUcodes/PB_TECS",proj4string=GDA94.56)

# function to create raster from shapfile
  create.raster <- function (s, mask.raster, raster.label, value=1, transform=FALSE) {
      
     if(transform==TRUE) {
       proj4string(s) <- GDA94
      s <- spTransform(s, GDA94.56)
       }
      
    r <- rasterize(s,mask.raster)
      r[!is.na(r)] <- value
      r <- mask(merge(r,mask.raster),mask.raster, filename=paste0(output.directory,raster.label), format="GTiff", overwrite=T)
      names(r) <- rep(raster.label,length(names(r)))
      
      plot(r, main=raster.label,zlim=c(0,3),legend=F,axes=F)
  
      return(r)
    }

# lower hunter mask
  LH.mask <- raster("~/GIS_data/Hunter/mask files/LH.mask.tif")
    LH.mask[!is.na(LH.mask)] <- 0

# lower hunter clipping mask
  LH.clipping.mask <- raster("~/GIS_data/Hunter/mask files/LH.clipping.mask.tif")
    LH.clipping.mask[!is.na(LH.clipping.mask)] <- 0

# greater hunter mask
  GH.mask <- raster("~/GIS_data/Hunter/mask files/GH.mask.tif")
    GH.mask[!is.na(GH.mask)] <- 0

# greater hunter clipping mask
  GH.clipping.mask <- raster("~/GIS_data/Hunter/mask files/GH.clipping.mask.tif")
    GH.clipping.mask[!is.na(GH.clipping.mask)] <- 0

# upper hunter mask
  UH.mask <- raster("~/GIS_data/Hunter/mask files/UH_HCCREMS.mask.tif")
    UH.mask[!is.na(UH.mask)] <- 0

# upper hunter clipping mask
  UH.clipping.mask <- raster("~/GIS_data/Hunter/mask files/UH_HCCREMS.clipping.mask.tif")
    UH.clipping.mask[!is.na(UH.clipping.mask)] <- 0
```

```{r create TEC names}

  TEC.data$TEC_Amy <- TEC.data$TECComments
    TEC.data$TEC_Amy <- gsub("Forms part of the Endangered Ecological Community ","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub("Equivalent to the Commonwealth Threatened Ecological Community ","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub("Equivalent to Endangered Ecological Community ","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub("Equivalent to the Endangered Ecological Community ","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub("This community may form part of the Endangered Ecological Community ","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub("This community forms part of the Endangered Ecological Community ","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub("This community may form part of; the Endangered Ecological Community ","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub("Where it occurs on coastal floodplains this community forms part of the Endangered Ecological Community ","",TEC.data$TEC_Amy)
        TEC.data$TEC_Amy <- gsub("Includes ","",TEC.data$TEC_Amy)

    TEC.data$TEC_Amy <- gsub("[[:punct:]]","",TEC.data$TEC_Amy)
    TEC.data$TEC_Amy <- gsub(" ","_",TEC.data$TEC_Amy)

# remove MU232 from list as it doesn't appear in either dataset
  TEC.data <- TEC.data[TEC.data$MapUnitID!="MU232",]
    

```

```{r}

 combine.rasters <- function (ghm.raster, pb.raster) {
  tryCatch({
            merge(pb.raster,ghm.raster)
            }, error = function(err){
              if(is.null(ghm.raster)==TRUE & is.null(pb.raster)==FALSE){
                return(pb.raster)
              } else if(is.null(pb.raster)==TRUE & is.null(ghm.raster)==FALSE){
                return(ghm.raster)
              } else cat("")
            })
  }


# create list of tecs
  tecs <- unique(TEC.data$TEC_Amy)

# create rasters for each tec from GHM & PB data
  for (t in seq(tecs)){
    cat("Rasterizing", tecs[t],"\n")
    mu.codes <- TEC.data$MapUnitID[TEC.data$TEC_Amy==tecs[t]]
      cat(" MU codes = ", as.character(mu.codes),"\n") 
    
    ghm.tec <- NULL
    pb.tec <- NULL
    
    try(ghm.tec <- create.raster(ghm[ghm$GHM_Native %in% mu.codes,],GH.mask,paste0("ghm.",tecs[t])),silent=T)
    try(pb.tec <- create.raster(pb[pb$GHMP_MU %in% mu.codes,],LH.mask,paste0("pb.",tecs[t])),silent=T)
       
    tec <- mask(combine.rasters(ghm.tec,pb.tec),GH.clipping.mask)
    plot(tec,main=tecs[t],axes=F,legend=F,box=F)
    writeRaster(tec,paste0(output.directory,"final_TECs/",tecs[t],"_GH.tif"), format="GTiff",overwrite=T)
        
  }


```

```{r convert to pdf}
# create pdf of tif files to send to HCCREMS for checking

  tif.files <- dir(paste0(output.directory,"final_TECs/"),"_GH.tif")
  
  pdf(paste0(output.directory,"final_TECs/GH_tecs.pdf"),pointsize=12, paper="a4r")
  
    for (i in seq(tif.files)){
      cat("Plotting", tif.files[i],"\n")
      r <- raster(paste0(output.directory,"final_TECs/",tif.files[i]))
        names(r) <- gsub("_GH","",names(r))
        tec <- gsub("_"," ",names(r))
        MUcodes <- TEC.data$MapUnitID[TEC.data$TEC_Amy==names(r)]
          MUcodes <- paste(MUcodes,sep=",",collapse=", ")
      plot(r, axes=F,box=F,legend=F)
        mtext(side=3,tec,line=3,adj=0)
        mtext(side=3,line=2,paste0("(",as.character(MUcodes),")"),cex=0.8)
      
    }
  
  dev.off()
```

```{r merge state & commonwealth TECs}
# identify matching tecs
  commonwealth <- c("Nominated_EC_Hinterland_LH.tif","Nominated_EC_Littoral_LH.tif")
  state <- c("Kurri_sand_swamp_woodland_in_the_Sydney_Basin_Bioregion_GH.tif","Littoral_Rainforest_in_the_NSW_North_Coast_Sydney_Basin_and_South_East_Corner_Bioregions_GH.tif")

  for (t in 1:2){
    cat("Merging", commonwealth[t],"&",state[t],"\n")
    s <- raster(paste0(output.directory,"final_TECs/",state[t]))
    c <- raster(paste0("~/GIS_data/Hunter/zonation/lower hunter/",commonwealth[t]))
      c[is.na(c)] <- 0  
      c <- mask(extend(c,s,value=0),s)
    merged.tec <- sum(c,s)
      merged.tec[merged.tec>0] <- 1
    writeRaster(merged.tec,paste0(output.directory,"final_TECs/merged_",state[t]),format="GTiff",overwrite=T)
  }

```


```{r export to zonation folder & cut TECs to LHSA/UHSA}

GH.tecs <- dir(paste0(output.directory,"/final_TECs/"),"_GH.tif")
  GH.tecs <- GH.tecs[!GH.tecs %in% state]

for (t in seq(GH.tecs)){
  cat("Clipping",GH.tecs[t],"\n")
  
  r <- raster(paste0(output.directory,"/final_TECs/",GH.tecs[t]))
  # save to GH zonation folder
    writeRaster(r, paste0("~/GIS_data/Hunter/zonation/greater hunter/",GH.tecs[t]),overwrite=T,format="GTiff")
  
  name <- gsub("_GH","",names(r))
   
  # clip to LH
    lh <- mask(crop(r,LH.mask),LH.clipping.mask)
    if(cellStats(lh,max)>0){
      writeRaster(lh,paste0("~/GIS_data/Hunter/zonation/lower hunter/",name,"_LH.tif"),overwrite=T,format="GTiff")
    }
  
  # clip to UH
    uh <- mask(crop(r,UH.mask),UH.clipping.mask)
    if(cellStats(uh,max)>0){
      writeRaster(uh,paste0("~/GIS_data/Hunter/zonation/upper hunter/",name,"_UH.tif"),overwrite=T,format="GTiff")
    }
  
  par(mfrow=c(1,3))
  plot(r,axes=F,box=F,legend=F)
     mtext(side=3,name,adj=0)
  plot(lh,axes=F,box=F,legend=F)
  plot(uh,axes=F,box=F,legend=F)
  rm(r,lh,uh)
}


```

```{r shutdown}
system("C:/Windows/system32/shutdown.exe -f -s -t 240")

```