---
title: "Create veg communities rasters for coal paper"
author: "Amy Whitehead"
date: "Wednesday, January 21, 2015"
output: html_document
---


```{r}
rm(list=ls())
start.time <- proc.time()
computer <- "//654cw-20990/Amy"

  envi.directory <- "~/GIS_data/Hunter/vegetation/"
  output.directory <- paste0(computer,"/GIS_data/Hunter/zonation/lower hunter coal paper/vegetation communities/")

setwd(output.directory)

packages(raster)
packages(rgdal)
packages(maptools)

source("C:/Users/awhitehead/Dropbox/Random R code/shp2raster.R")

LH.mask <- raster("~/GIS_data/Hunter/mask files/LH.urban.clipping.mask.tif")
LH.clipping.mask <- raster("~/GIS_data/Hunter/mask files/LH.clipping.mask.tif")

GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

 pre1750.shp <- readShapePoly("~/GIS_data/Hunter/All data from harddrive/Pre1750V03/ArcView/lhcc_pre1750veg.shp",proj4=CRS("+proj=utm +zone=56 +south +ellps=aust_SA +units=m +no_defs"),delete_null_obj=TRUE, force_ring=TRUE)
pre1750.shp <- spTransform(pre1750.shp,GDA94.56)
```

```{r create community rasters}

pct <- unique(pre1750.shp$MU_NAME)
  pct <- pct[!grepl("Water|Sand|Rocky Coast|Beach sands",pct)]

setwd(output.directory)

pb <- winProgressBar(title = "Clipping community rasters", label = "%",min = 0, max = length(pct), initial = 0, width = 300)

for(i in seq(pct)){
  extant <- shp2raster(pre1750.shp[pre1750.shp$MU_NAME==pct[i],],mask.raster = LH.clipping.mask,label=paste0("extant/",gsub("\\/","",pct[i])),value=1,bkg=0)
  if(cellStats(extant,max)!=1) {
    file.remove(paste0("extant/",as.character(pct[i]),".tif"))
    } else {
      pre1750 <- shp2raster(pre1750.shp[pre1750.shp$MU_NAME==pct[i],],mask.raster = LH.mask,label=paste0("pre1750/",gsub("\\/","",pct[i]),"_pre1750"),value=1,bkg=0)
    }
  rm(extant,pre1750)
  setWinProgressBar(pb, i, title = NULL, label = NULL)
  gc()
}

close(pb)
```

