---
title: "Summarise MaxEnt outputs for HCCREMS & DotE report"
author: "Amy Whitehead"
date: "Thursday, October 30, 2014"
output: html_document
---

```{r}
rm(list=ls())

library(dplyr)
library(raster)
library(maptools)

# computer <- "~" #My computer
#computer <- "Z:/Amy" #Super computer
computer <- "//654cw-20990/Amy"

source("C:/Users/awhitehead/Dropbox/Random R code/rbind.columns.r")

# define paths for input and output files
  maxent.dir <- paste0(computer,'/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/')

  taxa <- c("birds","mammals","plants","reptiles","amphibians")

  protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))

  # import biodiversity feature names
#   names <- as.vector(read.table(paste0(input_path,'LH.extant.zonation.weighted.spp'), header=F, sep='\t')[,6])

  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

  GH.shp <- readShapePoly("C:/Users/awhitehead/Documents/GIS_data/Hunter/Plans/HCCREMS_AreaOfInterest/HCCREMS_AoI.shp", proj4=GDA94)
    GH.shp <- spTransform(GH.shp,GDA94.56)
  GH.clipping.mask <- raster(paste0(computer,"/GIS_Data/Hunter/mask files/GH_PM.clipping.mask.tif"))

```

```{r useful functions}
trim <- function (x) gsub("^\\s+|\\s+$", "", x)

strip.names <- function(x){
  trim(gsub("_"," ",gsub("extant\\/|\\_GH|\\.tif|SSI|SDM|DotE\\/|\\//|654cw-20990|\\/|Amy|GIS_data|Hunter|zonation|greater hunter","",x)))
}


```

```{r extract maxent results}
envi.parameters <- c("Taxa","Family","Species","Status","MNES","N.records","Training.samples","N.trees","Test.AUC","AUC.Standard.Deviation","cold_temp","hot_temp","mean_rain","seasonal_rain","mean_solar","slope","rugg1000","terr1000","wetness","final_vegetation","2000Dry_sclerophyll_forests","2000Rainforests","2000Wet_sclerophyll_forests","soil")

for (i in seq(taxa)){
  maxentResults.CV <- read.csv(paste0(maxent.dir,taxa[i],"/pre1750v2/CV/MaxentResults.csv"))
    maxentResults.CV <- maxentResults.CV[grepl("average",maxentResults.CV$Species),]
  maxentResults.Full <- read.csv(paste0(maxent.dir,taxa[i],"/pre1750v2/Full/MaxentResults.csv"))
  parameters <- c("Species","X.Training.samples","Test.AUC","AUC.Standard.Deviation",names(maxentResults.Full[grepl("permutation.importance",names(maxentResults.Full))]))
  
  maxentResults.CV <- maxentResults.CV[,names(maxentResults.CV) %in% as.character(parameters[1:4])]
  
  maxentResults.Full <- maxentResults.Full[,names(maxentResults.Full) %in% as.character(parameters[c(5:14)])]
  
  maxentResults <- cbind(maxentResults.CV,maxentResults.Full)
  
  names(maxentResults) <- gsub("X\\.|X|.permutation.importance","",names(maxentResults))

maxentResults$Species <- gsub("_"," ",gsub(" \\(average\\)","",maxentResults$Species))
maxentResults <- maxentResults[order(maxentResults$Species),]
# maxentResults[,5:ncol(maxentResults)] <- round(maxentResults[,5:ncol(maxentResults)],2)
#  maxentResults$Test.AUC <- paste0(round(maxentResults$Test.AUC,3)," (",round(maxentResults$AUC.Standard.Deviation,3),")")
# maxentResults <- maxentResults[,!names(maxentResults) %in% "AUC.Standard.Deviation"]
maxentResults$Taxa <- taxa[i]
maxentResults$Family <- protected.species$Family[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$Status <- protected.species$combined.status[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$MNES <- protected.species$mnes[protected.species$Scientific.Name %in% maxentResults$Species]
maxentResults$N.records <- protected.species$greater.hunter[protected.species$Scientific.Name %in% maxentResults$Species]
envi.order <- envi.parameters[envi.parameters %in% names(maxentResults)]  
maxentResults <- maxentResults[,envi.order]

assign(paste0(taxa[i],"_MR"),maxentResults)
 write.csv(maxentResults,paste0(maxent.dir,taxa[i],"_DotE report - maxent summary.csv"),row.names=F) 
}

```


```{r tecs}
  maxentResults <- read.csv(paste0(maxent.dir,"/tecs/BRT/contributions.csv"))
   parameters <- c("tec","n.records","cv.roc.mean","cv.roc.se",names(maxentResults[grepl("permutation.importance",names(maxentResults))]))
  
  maxentResults <- maxentResults[,!names(maxentResults) %in% c("lr","cv.correlation.mean","cv.correlation.se","cv.deviance.mean","cv.deviance.se")]
  
  names(maxentResults) <- gsub("X","",names(maxentResults))
  names(maxentResults)[names(maxentResults) %in% c("tec","ntrees","cv.roc.mean","cv.roc.se","n.records")] <- c("Species","N.trees","Test.AUC","AUC.Standard.Deviation","N.records")
maxentResults <- maxentResults[order(maxentResults$Species),]
# maxentResults[,!names(maxentResults) %in% c("Species","N.trees","Test.AUC","AUC.Standard.Deviation","N.records")] <- round(maxentResults[,!names(maxentResults) %in% c("Species","N.trees","Test.AUC","AUC.Standard.Deviation","N.records")],2)
#  maxentResults$Test.AUC <- paste0(round(maxentResults$Test.AUC,3)," (",round(maxentResults$AUC.Standard.Deviation,3),")")
# maxentResults <- maxentResults[,!names(maxentResults) %in% "AUC.Standard.Deviation"]
maxentResults$Taxa <- "EEC"
maxentResults$Family <- ""

envi.order <- envi.parameters[envi.parameters %in% names(maxentResults)]  
maxentResults <- maxentResults[,envi.order]

assign(paste0("EEC_MR"),maxentResults)
 write.csv(maxentResults,paste0(maxent.dir,"EEC_DotE report - maxent summary.csv"),row.names=F)  

```

```{r combine outputs}
output <- rbind.columns(birds_MR,mammals_MR)
  output <- rbind.columns(output,plants_MR)
  output <- rbind.columns(output,reptiles_MR)
  output <- rbind.columns(output,amphibians_MR)
  output <- rbind.columns(output,EEC_MR)

output <- output[order(output$Species),]
envi.order <- envi.parameters[envi.parameters %in% names(output)] 
output <- output[,envi.order]

write.csv(output,paste0(maxent.dir,"GH DotE report - maxent summary.csv"),row.names=F)

poorly.modelled <- output[output$Test.AUC<0.7,c("Taxa","Species","Status","MNES","N.records","Test.AUC","AUC.Standard.Deviation")]
write.csv(poorly.modelled,paste0(maxent.dir,"DotE report - poorly modelled species.csv"),row.names=F)
```

```{r mean summary table}
names(output) <- gsub("2000","",names(output))

summary <- {
  output %>%
    group_by(Taxa) %>%
      summarise(
        N = n(),
        AUC.mean = mean(Test.AUC, na.rm=T),
        AUC.se = se(Test.AUC),
        cold_temp.mean = mean(cold_temp, na.rm=T),
        cold_temp.se = se(cold_temp),
        hot_temp.mean = mean(hot_temp, na.rm=T),
        hot_temp.se = se(hot_temp),
        mean_rain.mean = mean(mean_rain, na.rm=T),
        mean_rain.se = se(mean_rain),
        seasonal_rain.mean = mean(seasonal_rain, na.rm=T),
        seasonal_rain.se = se(seasonal_rain),
        mean_solar.mean = mean(mean_solar),
        mean_solar.se = se(mean_solar),
        slope.mean = mean(slope, na.rm=T),
        slope.se = se(slope),
        rugg1000.mean = mean(rugg1000, na.rm=T),
        rugg1000.se = se(rugg1000),
        terr1000.mean = mean(terr1000, na.rm=T),
        terr1000.se = se(terr1000),
        wetness.mean = mean(wetness, na.rm=T),
        wetness.se = se(wetness),
        final_vegetation.mean = mean(final_vegetation, na.rm=T),
        final_vegetation.se = se(final_vegetation),
        Dry_sclerophyll_forests.mean = mean(Dry_sclerophyll_forests, na.rm=T),
        Dry_sclerophyll_forests.se = se(Dry_sclerophyll_forests),
        Rainforests.mean = mean(Rainforests, na.rm=T),
        Rainforests.se = se(Rainforests),
        Wet_sclerophyll_forests.mean = mean(Wet_sclerophyll_forests, na.rm=T),
        Wet_sclerophyll_forests.se = se(Wet_sclerophyll_forests),
        soil.mean = mean(soil, na.rm=T),
        soil.se = se(soil)
        )
}

summary.table <- as.data.frame(summary)
  summary.table <- as.data.frame(t(summary.table[,2:ncol(summary.table)]))
  names(summary.table) <- c("EEC","amphibians","birds","mammals","plants","reptiles")
  summary.table <- summary.table[,c("amphibians","birds","mammals","plants","reptiles","EEC")]
  summary.table <- round(summary.table,2)

envi.parameters <- gsub("2000|Test\\.","",envi.parameters)

for(i in seq(envi.parameters)){
  if(length(nrow(summary.table[grepl(envi.parameters[i],row.names(summary.table)),])==2)){
    test <- summary.table[grepl(envi.parameters[i],row.names(summary.table)),]
    for(k in 1:6){
      test[1,k] <- paste0(test[1,k]," (",test[2,k],")")
      test[1,k] <- gsub("NaN \\(NA\\)|NA \\(NA\\)","\\-",as.character(test[1,k]))
    }
  summary.table[row.names(summary.table)==paste0(envi.parameters[i],".mean"),] <- test[1,]
  rm(test)
  }
}

summary.table <- summary.table[!grepl("\\.se",row.names(summary.table)),]
row.names(summary.table) <- gsub("\\.mean","",row.names(summary.table))
  
write.csv(summary.table,paste0(maxent.dir,"GH DotE report - maxent parameter summary.csv"),row.names=T)

```


```{r plot AUC values}

output$Taxa <- factor(output$Taxa, levels=c("amphibians","birds","mammals","plants","reptiles","EEC"))

png(paste0(maxent.dir,"GH_AUC_boxplot.png"),width=15,height=15,units = "cm",pointsize=12,bg="transparent",res=300)
par(las=1,mar=c(4,6,2,2))
boxplot(Test.AUC~Taxa, data=output, xlab="AUC",horizontal = T)
abline(v=0.7,lty=3)
dev.off()


```

```{r species richness & spatial uncertainty}

gh.sdms <- dir("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/extant",pattern="SDM_GH.tif",full.names=T)

  gh.sdms.stack <- stack(gh.sdms[!grepl(gsub(" ","_",paste0(poorly.modelled$Species,collapse="|")),gh.sdms)])
  
  species.richness <- sum(gh.sdms.stack)
    writeRaster(species.richness,paste0(maxent.dir,"GH.species.richness.tif"))

  species.richness <- raster(paste0(maxent.dir,"GH.species.richness.tif"))
  mean.uncertainty <- raster(paste0("//654cw-20990/Amy/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/mean.uncertainty_2015-01-09.tif"))
    mean.uncertainty <- mask(crop(mask(mean.uncertainty,GH.clipping.mask),GH.shp),GH.shp)
  mean.range.cv <- cellStats(mean.uncertainty,range)


png(paste0(maxent.dir,"GH richness & uncertainty.png"),width=17,height=10,units="cm",res=300,pointsize=12,bg="transparent")
  par(mfrow=c(1,2),mar=c(3,0,0,0),oma=c(2,0,1,0),xpd=NA)
  plot(GH.shp,col="lightgrey",axes=F)  
    plot(species.richness,axes=F,box=F,legend=F,col=brewer.pal(9,"YlGnBu"),add=T)
    plot(GH.shp, add=T)
mtext("A)",side=3,line=0,cex=1,adj=0.05,font=2)
image.plot(species.richness,legend.only=TRUE,zlim=c(0,30),nlevel=100, col=brewer.pal(9,"YlGnBu"),axis.args=list(at=c(0,30), labels=c("Low","High"), cex.axis=0.7,adj=0.5),legend.args=list(text='Relative richness', side=3, font=2, line=0.75, cex=0.7),legend.width=0.5,legend.shrink=0.5,horizontal = T,smallplot=c(0.25,0.75,0.05,0.075))

plot(GH.shp,col="lightgrey",axes=F)
plot(mean.uncertainty,axes=F,add=T,legend=F,col=brewer.pal(9,"OrRd"))
    image.plot(legend.only=TRUE,zlim=mean.range.cv, nlevel=100, col=brewer.pal(9,"OrRd"),axis.args=list(at=mean.range.cv, labels=c(paste0("Low","\n","(CV=",round(mean.range.cv[1],2),")"),paste0("High","\n","(CV=",round(mean.range.cv[2],2),")")), cex.axis=0.7,adj=0.5),legend.args=list(text='Predictive uncertainty', side=3, font=2, line=0.75, cex=0.7),legend.width=0.5,legend.shrink=0.5,horizontal = T,smallplot=c(0.25,0.75,0.05,0.075))
    plot(GH.shp, add=T)
mtext("B)",side=3,line=0,cex=1,adj=0.05,font=2)

dev.off()

```
