Create sampling bias layer 
========================================================

Use maxent data to create a sampling bias layer using the Moore neighbourhood

```{r setup}
rm(list=ls())
packages(raster)
packages(rgdal)
packages(maptools)

setwd("~/GIS_data/Hunter/Maxent_files/ghm_environmental_data/")

hccrems <- raster("hccrems_mask.asc")
  hccrems[!is.na(hccrems)] <- 0

#function to make a circular weights matrix of given radius and resolution
#NB radius must be an even multiple of res!
make_circ_filter<-function(radius, res){
  require(raster)
  circ_filter<-matrix(NA, nrow=1+(2*radius/res), ncol=1+(2*radius/res))
  dimnames(circ_filter)[[1]]<-seq(-radius, radius, by=res)
  dimnames(circ_filter)[[2]]<-seq(-radius, radius, by=res)
  sweeper<-function(mat){
    for(row in 1:nrow(mat)){
      for(col in 1:ncol(mat)){
        dist<-sqrt((as.numeric(dimnames(mat)[[1]])[row])^2 +
          (as.numeric(dimnames(mat)[[1]])[col])^2)
        if(dist<=radius) {mat[row, col]<-1}
      }
    }
    return(mat)
  }
out<-sweeper(circ_filter)
return(out)
}

# function to sum the values in the circular filter and divides by the number of cells 
##(removing all cells with NA values)
percent.cover <- function(x){ sum(x,na.rm=T)/sum(cf, na.rm=T)}

 generate.pc.ascii <- function (filename, mask) {
    sample.raster <- raster(filename)
    
    cat("\n","Loaded",filename)
    
    sample.raster <- resample(sample.raster,mask, method="bilinear")

  # calculate the percentage cover within the circular filter
    cat("\n","Calculating % cover of",filename," within",radius,"m radius")
    r_filt <- focal(sample.raster, w=cf, fun=percent.cover)*mask
  
    par(mfrow=c(1,2))
    plot(sample.raster, main=filename, axes=F) #original data
    plot(r_filt, main=paste0(radius,"m ",filename), axes=F) #filtered data
  
  writeRaster(r_filt, paste0("ascii files/veg.",radius,filename), overwrite=TRUE)
    cat("\n","Saved",paste0("veg",radius,filename),"in",paste0(getwd(),"/ascii files"),"\n","\n")
  }

rbind.match.columns <- function (input1,input2) {
    n.input1 <- ncol(input1)
    n.input2 <- ncol(input2)
    
    if(n.input2 < n.input1) {
      TF.names <- which(names(input2) %in% names(input1))
      column.names <- names(input2[,TF.names])
      } else {
        TF.names <- which(names(input1) %in% names(input2))
        column.names <- names(input1[,TF.names])
      }
    
    output <- rbind(input1[,column.names], input2[,column.names])
  }


combine.records <- function (NC.records, SB.records) {
  tryCatch({
            rbind.match.columns(NC.records,SB.records)
            }, error = function(err){
              if(is.null(NC.records)==TRUE & is.null(SB.records)==FALSE){
                return(SB.records)
              } else if(is.null(SB.records)==TRUE & is.null(NC.records)==FALSE){
                return(NC.records)
              } else cat("")
            })
  }


```

```{r import data}
setwd("~/GIS_data/Hunter/species point data/")

# the taxanomic blocks that the data were downloaded in
taxa <- c("mammals", "amphibians", "plants", "reptiles","birds","arthropods")

# loop through each taxonomic group and extract records based on the threatened species list
for (k in seq(taxa)){
  cat("\n", "Extracting records for",taxa[k],"from ALA", "\n")  
  
  tryCatch( {
    BB.input <- read.csv(paste0("ALA downloads/Brigalow Belt South ",taxa[k],".csv"))
    BB.input <- BB.input[,c("Scientific.Name", "Latitude...processed","Longitude...processed")]
    SB.input <- read.csv(paste0("ALA downloads/Sydney Basin ",taxa[k],".csv"))
          SB.input <- SB.input[,c("Scientific.Name", "Latitude...processed","Longitude...processed")]
    NNC.input <- read.csv(paste0("ALA downloads/NSW North Coast ",taxa[k],".csv"))
          NNC.input <- NNC.input[,c("Scientific.Name", "Latitude...processed","Longitude...processed")]


    NM.NC.input <- read.csv(paste0("NSW Atlas downloads/NSW North Coast ",taxa[k],".csv"))
      colnames(NM.NC.input)[8] <- "Scientific.Name"
      NM.NC.input <- NM.NC.input[,c("Scientific.Name", "Latitude_GDA94","Longitude_GDA94")]

  NM.SB.input <- read.csv(paste0("NSW Atlas downloads/Sydney Basin ",taxa[k],".csv"))
    colnames(NM.SB.input)[8] <- "Scientific.Name"
    NM.SB.input <- NM.SB.input[,c("Scientific.Name", "Latitude_GDA94","Longitude_GDA94")]

  LR.input <- read.csv(paste0("NSW Atlas downloads/Liverpool Range ",taxa[k],".csv"))
    colnames(LR.input)[8] <- "Scientific.Name"
    LR.input <- LR.input[,c("Scientific.Name", "Latitude_GDA94","Longitude_GDA94")]

    
    }, warning = function(e) {cat("")})
     
      all.records.ALA <- combine.records(BB.input, SB.input)
        all.records.ALA <- combine.records(all.records.ALA, NNC.input)
#         all.records.ALA <- all.records.ALA[,c("Scientific.Name", "Latitude...processed","Longitude...processed")]
        colnames(all.records.ALA) <- c("Species", "Latitude", "Longitude")
        all.records.ALA$database <- "ALA"
    
      all.records.NM <- combine.records(NM.NC.input, NM.SB.input)
        all.records.NM <- combine.records(all.records.NM, LR.input)
#         all.records.NM <- all.records.NM[,c("Scientific.Name", "Latitude_GDA94","Longitude_GDA94")]
        colnames(all.records.NM) <- c("Species", "Latitude", "Longitude")
        all.records.NM$database <- "NM"
  all.records <- rbind(all.records.ALA,all.records.NM)
  all.records <- all.records[complete.cases(all.records),]
  coordinates(all.records) <- c("Longitude","Latitude")
     proj4string(all.records) <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

  # transform to new projection
  all.records <- spTransform(all.records, CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"))
  
  all.records <- as.data.frame(all.records)
  all.records$Latitude[all.records$database=="ALA"] <- all.records$Latitude[all.records$database=="ALA"] + 176.9
  all.records$Longitude[all.records$database=="ALA"] <- all.records$Longitude[all.records$database=="ALA"] + 104
  coordinates(all.records) <- c("Longitude","Latitude")

   # names(all.records)[2:3] <- c("easting","northing")
  
        cell <- cellFromXY(hccrems,all.records)
      all.records <- all.records[!duplicated(cell),]
 
  filename <- paste0("all_records_",taxa[k])
  
  writePointsShape(all.records,filename )
  assign(filename, all.records) 
  BB.input <-NULL;SB.input<-NULL;NNC.input<-NULL;NM.SB.input<-NULL;NM.NC.input<-NULL;LR.input<-NULL
    rm(all.records,all.records.NM,all.records.ALA)
  gc()
  }

```

```{r normalise sampling bias}
setwd("~/GIS_data/Hunter/Maxent_files/ghm_environmental_data/sampling bias/")

(sb.files <- dir(pattern=".tif$", recursive=T, full.names=F))
sb.rasters <- lapply(sb.files,raster)

region.raster <- raster("~/GIS_data/Hunter/Maxent_files/ghm_environmental_data/standardised_rasters/hccrems_mask.asc")


for(i in 1:length(sb.files)){
  r <- sb.rasters[[i]]
  cat("Normalising & exporting", names(r), "\n")  
    r <- setMinMax(r)
    r <- (r - minValue(r))/(maxValue(r)-minValue(r))+0.05
#     r <- mask(resample(r,region.raster),region.raster)
  plot(r,main=names(r))
  writeRaster(r,paste0(names(r),".tif"),overwrite=T)  
}

```


