---
title: "Figures for coal paper"
author: "Amy Whitehead"
date: "Friday, October 31, 2014"
output: html_document
---

```{r setup}
rm(list=ls())
library(raster)
library(rgdal)
library(maptools)
library(RColorBrewer)
library(fields)

# computer <- "~" #My computer
#computer <- "Z:/Amy" #Super computer
computer <- "//654cw-20990/Amy"

input_path <- "//654cw-20990/Amy/GIS_data/Hunter/zonation/lower hunter coal paper/"
output_path <- "//654cw-20990/Amy/GIS_data/Hunter/zonation/lower hunter coal paper/"

# uia_dir <- "~/GIS_data/Hunter/Scenarios/LH coal paper UIA/Shapefiles for Amy"

# projections 
  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

```

```{r import data}
LH.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.mask.tif"))
LH.clipping.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.clipping.mask.tif"))
# LH administrative boundary
  GH.shp <- readShapePoly("~/GIS_data/Hunter/All data from harddrive/From HCCREMS/Boundaries/AoI/HCCREMS_LGA.shp",proj4=GDA94)
  LH.shp <- readShapePoly("~/GIS_data/Hunter/All data from harddrive/From DO/OEH_Lower_Hunter_18122012/Administrative/5_LGAs_StudyArea.shp", proj4=GDA94.56)
    LH.shp <- unionSpatialPolygons(LH.shp,LH.shp$WBCode) 

condition <- raster(paste0(input_path,"LH.cond.v2.tif"))
coal <- raster(paste0(input_path,"scenarios/mining_100_LHcoal.tif"))
pa <- raster(paste0(input_path,"masks/PAv2_0mining_mask.tif"))
  pa[pa==3] <- 0

coal.na <- coal
  coal.na[is.na(coal.na)] <- 0
pa.coal <- pa+coal.na
  pa.coal[pa.coal==0] <- NA

cas.cun.retention <- raster(paste0(input_path,"Casuarina_cunninghamiana_subsp._cunninghamiana_pre1750_SDM.LH_retention.tif"))
  cas.cun.retention[cas.cun.retention==0] <- NA
cas.cun.extant <- raster("//654cw-20990/Amy/GIS_data/Hunter/zonation/lower hunter/extant/Casuarina_cunninghamiana_subsp._cunninghamiana_SDM.LH.tif")

aus.shp <- readShapePoly("//654cw-20990/Amy/GIS_data/Australia/australia_one polygon.shp")
newcastle <- spTransform(LH.shp,GDA94)
```

```{r Figure 1}
png("Figure1.png",width=190,height=120,units="mm",res=300,bg="transparent")
par(mfrow=c(2,2),oma=c(1,1,0,0),mar=c(1,0.5,0.5,0.5),xpd=NA)
plot(LH.clipping.mask,col='lightgrey',axes=F,box=F,legend=F)
#   plot(LH.clipping.mask,col='lightgrey',add=T,legend=F)
  plot(pa.coal,breaks=c(seq(0,1,0.2),4,seq(4.1,5,0.2)),col=c(brewer.pal(9,'Greys')[5:9],brewer.pal(9,'Greens')[4],brewer.pal(9,'Greens')[5:9]),legend=F,add=T)
  plot(LH.shp,add=T)
legend("bottomright",fill=c(brewer.pal(9,'Greens')[4],"lightgrey"),legend=c("Protected areas","Remnant vegetation"),bty="n",cex=0.8,inset=c(0,0.01))
image.plot(add = T,col=brewer.pal(9,'Greys')[5:9],legend.only=T,zlim=c(0,1),axis.args=list(at=c(0,1),labels=c("Low: 0","High: 1"), cex.axis=0.6),legend.args=list(text='Probability of mining', side=3, cex=0.6,adj=0),horizontal=T,smallplot=c(0.01,0.21,0.1,0.12))
 
# mtext(x=356981, y=6307763, "Low: 0",cex=0.5)
# text(x=376981, y=6296766, "High: 0",cex=0.5)
 mtext("A",side=3,adj = 0,font = 2,line =-1.5)

# plot(LH.clipping.mask,col='whitesmoke',axes=F,box=F,legend=F)
plot(condition,breaks=seq(0,1,0.25),col=c(brewer.pal(4,'Greens')),axes=F,box=F,legend=F)
#   plot(LH.clipping.mask,col='lightgrey',add=T,legend=F)
plot(LH.shp,add=T)
image.plot(add = T,col=brewer.pal(9,'Greens'),legend.only=T,zlim=c(0,1),axis.args=list(at=c(0,1),labels=c("Low: 0","High: 1"), cex.axis=0.6),legend.args=list(text='Condition', side=3, cex=0.7,adj=0),horizontal=T,smallplot=c(0.01,0.21,0.1,0.12))
#   legend(axis.args=list(at=c(0,1),labels=c("Low: 0","High: 1"), cex.axis=0.6),   legend.args=list(text='Condition', side=3, font=2, cex=0.7),legend.shrink=0.3,legend.width=0.6,"topleft")
# legend("topleft",legend(axis.args=list(at=c(0,1),labels=c("Low: 0","High: 1"), cex.axis=0.6),   legend.args=list(text='Condition', side=3, font=2, cex=0.7),legend.shrink=0.3,legend.width=0.6,"topleft"))
mtext("B",side=3,adj = 0,font = 2,line=-1.5)

plot(LH.clipping.mask,col='lightgrey',axes=F,box=F,legend=F)
  plot(cas.cun.extant,zlim=c(20,1000),legend=F,add=T,col=brewer.pal(9,"Greens")[3:9])
  plot(LH.shp,add=T)
  mtext("C",side=3,adj = 0,font = 2,line=-1.5)
image.plot(add = T,col=brewer.pal(9,'Greens'),legend.only=T,zlim=c(0,1),legend.shrink=0.5,legend.width=1,axis.args=list(at=c(0,1),labels=c("Low: 0","High: 1"), cex.axis=0.6),legend.args=list(text='Likelihood of occurrence', side=3, cex=0.7,adj=0),horizontal=T,smallplot=c(0.01,0.21,0.1,0.12),legend.line=0)
scalebar(d = 30000,type = "bar",label = c(0,15,30),cex=0.7,xy = c(295500,6385000),xpd=NA)

plot(LH.clipping.mask,col='lightgrey',axes=F,box=F,legend=F)
  plot(cas.cun.retention,legend=F,add=T,col=brewer.pal(9,"Greens")[3:9])
  plot(LH.shp,add=T)
  image.plot(add = T,col=brewer.pal(9,'Greens'),legend.only=T,zlim=c(0,1),legend.shrink=0.5,legend.width=1,axis.args=list(at=c(0,1),labels=c("Low: 0","High: 1"), cex.axis=0.6),legend.args=list(text='Restoration potential', side=3, cex=0.65,adj=0),horizontal=T,smallplot=c(0.01,0.21,0.1,0.12))

  mtext("D",side=3,adj = 0,font = 2,line=-1.5)

par(new = TRUE)
par(fig = c(0.78, 1, 0.0, 0.3),mar=c(1.5,1.5,1.5,1.5))
plot(aus.shp,xlim=c(131,136),ylim=c(-44,-10),lwd=0.75,border=T,col="white")
plot(GH.shp,add=T,col=brewer.pal(9,"Greens")[9],border=brewer.pal(9,"Greens")[9])
# box(which="plot")

dev.off()

```


```{r import priority data}
rank.files <- c("Output/output_LHcoal_extant_0.5mining.rank.asc","Output/output_LHcoal_restore_0.5mining_PA.rank.asc","Output/output_LHcoal_retention_0.5mining_PA.rank.asc")
rank.rasters <- stack(paste0(input_path,rank.files))
mask.files <- dir(paste0(input_path,"masks/"), pattern="restore.tif$")
uia.mask <- raster("//654cw-20990/Heini/RSP/HV/All_UIA_mask.tif")

load(paste0(input_path,"results/Breaks"))


results <- read.table(paste0(input_path,"results/Offsets_results_AbsVal.txt"),header=T)
  results$mining.pct <- seq(5,100,5)
results.UIA <- read.table(paste0(input_path,"results/Offsets_results_AbsValue_UIA.txt"),header=T)
  results.UIA$mining.pct <- seq(5,100,5)

# uia.shapefiles <- dir(uia_dir,pattern=".shp$")
# #   ## hack until I get the missing shx file ##
# #   uia.shapefiles <- uia.shapefiles[!grepl("Allagg1.shp",uia.shapefiles)]
# setwd(uia_dir)
# 
# for(i in seq(uia.shapefiles)){
#   assign(uia.shapefiles[i], crop(readOGR(dsn=".",layer=gsub(".shp","",uia.shapefiles[i])),LH.mask))
# }
# 
# setwd(input_path)

# merge all shapefiles together

# test <- gUnion(gBuffer(get(uia.shapefiles[1]),width=0),gBuffer(get(uia.shapefiles[2]),width=0))
#   test <- gUnion(test,gBuffer(get(uia.shapefiles[3]),width=0))
#   test <- gUnion(test,gBuffer(get(uia.shapefiles[4]),width=0))
  
```

```{r heini's code}
threshold <- seq(0.05,1,0.05)

  font <- 1
  pa.col <- '#00A600FF'
  mines.col <- '#4D4D4D'
  protect.col <- '#EAB64EFF'
  restore.col <- '#0080FFFF'
  bg.col <- "#F2F2F2FF"
  uia.col <- '#4D4D4D'
  uia.alpha <- 0.4

# col.3 <- c('#F2F2F2FF', '#EAB64EFF', '#00A600FF')
#  col.4 <- c('#F2F2F2FF', '#EAB64EFF', '#0080FFFF', '#00A600FF')
#   col.4 <- c('#F2F2F2FF', 'orange2', '#0080FFFF', '#00A600FF')
#   col.legend <- c('#00A600FF', '#EAB64EFF', '#0080FFFF', '#4D4D4D')

for (i in seq(threshold)){

  # save maps showing offsetting results
  restore.mask <- raster(paste0('//654cw-20990/Amy/GIS_data/Hunter/zonation/lower hunter coal paper/masks/PAv2_', threshold[i], 'mining_mask.restore.tif'))
  mines.mask <- restore.mask
  mines.mask[which(mines.mask[]>1)] <- NA
  
  out.protect <- raster(paste0('//654cw-20990/Amy/GIS_data/Hunter/zonation/lower hunter coal paper/Output/output_LHcoal_extant2_', threshold[i], 'mining.rank.asc'))
    out.protect[which(out.protect[]>offset.breaks[i,"protected.pre.new"])] <- 3
    out.protect[which(out.protect[]>offset.breaks[i,"offset.fraction.protect"] & out.protect[]<(offset.breaks[i,"protected.pre.new"]) & restore.mask[]==2)] <- 2
    out.protect[which(out.protect[]<2)] <- 1
  
  out.both <- raster(paste0('//654cw-20990/Amy/GIS_data/Hunter/zonation/lower hunter coal paper/Output/output_LHcoal_retention_', threshold[i], 'mining_PA.rank.asc'))
  out.both[which(out.both[]>offset.breaks[i,"protected.pre.new"])] <- 4
  out.both[which(out.both[]>offset.breaks[i,"offset.fraction.both"] & restore.mask[]==3)] <- 3
  out.both[which(out.both[]>offset.breaks[i,"offset.fraction.both"] & restore.mask[]==2)] <- 2
  out.both[which(out.both[]<2)] <- 1
  # calculate % of top priorities allocated for restoration in Scenario 2
#   results[i,11] <- freq(out.both)[which(freq(out.both)[,1]==3),2]/sum(freq(out.both)[which(freq(out.both)[,1] %in% c(3,2)),2])
  
  out.restore <- raster(paste0('//654cw-20990/Amy/GIS_data/Hunter/zonation/lower hunter coal paper/Output/output_LHcoal_restore_', threshold[i], 'mining_PA.rank.asc'))
  out.restore[which(out.restore[]>offset.breaks[i,"protected.pre.new"])] <- 3
  out.restore[which(out.restore[]>offset.breaks[i,"offset.fraction.restore"] & out.restore[]<(offset.breaks[i,"protected.pre.new"]) & restore.mask[]==3)] <- 2
  out.restore[which(out.restore[]<2)] <- 1
  # checking that all top priorities are indeed on the restoration area
#   results[i,12] <- freq(out.restore)[which(freq(out.restore)[,1]==3),2]/sum(freq(out.restore)[which(freq(out.restore)[,1] %in% c(3,2)),2])
 
# setwd("C:/Users/awhitehead/Downloads/")

  png(paste0('Offsets_', threshold[i], 'mining_impacts_Amy.png'), width = 15, height = 12, units="cm",res=300,bg="transparent",pointsize=12)
  
  par(mfrow=c(2,2), mar=c(1,1,2.5,0.5),las=1,xpd=NA)
  plot(out.protect, col=c(bg.col,protect.col,pa.col), breaks=c(0,1,2,3), legend=F, box=F, axes=F, main='Protect', cex.main=font)
#     plot(out.protect, col=c(bg.col,protect.col,restore.col,pa.col), breaks=c(0,offset.fraction.restore,(1-protected.pre.new),1), legend=F, box=F, axes=F, main='Protect', cex.main=font) 
    plot(mines.mask, add=T, col=mines.col, legend=F)
    plot(LH.shp,col=NA,border="grey",add=T)
    plot(uia.mask,add=T,col = uia.col,alpha=uia.alpha,zlim=c(1,1),legend=F)

legend('bottomleft', legend=c('Protected areas', 'Offset: Protect', 'Offset: Restore', 'Area mined'), fill=c(pa.col,protect.col,restore.col,mines.col), bty='n', cex=1,horiz =T,xpd = NA )
  
  plot(out.both, col=c(bg.col,protect.col,restore.col,pa.col), breaks=c(0,1,2,3,4), legend=F, box=F, axes=F, main='Both', cex.main=font)
    plot(mines.mask, add=T, col=mines.col, legend=F)
    plot(LH.shp,col=NA,border="grey",add=T)
    plot(uia.mask,add=T,col = uia.col,alpha=uia.alpha,zlim=c(1,1),legend=F)
  
  plot(out.restore, col=c(bg.col,restore.col,pa.col), breaks=c(0,1,2,3), legend=F, box=F, axes=F, main='Restore', cex.main=font)
    plot(mines.mask, add=T, col=mines.col, legend=F)
    plot(LH.shp,col=NA,border="grey",add=T)
    plot(uia.mask,add=T,col = uia.col,alpha=uia.alpha,zlim=c(1,1),legend=F)
  
  par(mar=c(4,4,1,2),las=1)
    plot(results$mining.pct,results$Mean.loss,type="l",bty="n",xlim=c(0.05,100),ylim=c(0,0.7),ylab="Proportion of distributions lost",xlab="Titles mined",axes=F)
    abline(v=results$mining.pct[i],lty=3,col="grey")
    axis(side=1,at=c(5,50,100),labels=c("5%","50%","100%"))
    axis(side=2,at=c(0.00,0.35,0.70),labels=c("0.00","0.35","0.70"))
    lines(results$mining.pct,results$Max.loss, lty=2)
    lines(results$mining.pct,results.UIA$Mean.loss, lty=1,col=mines.col)
    lines(results$mining.pct,results.UIA$Max.loss, lty=2,col=mines.col)
      
    
  #   plot(empty.plot, col='white', legend=F, box=F, axes=F,)
  
  dev.off()

}

```
