---
title: "Recut old SDMS for LH coal paper"
author: "Amy Whitehead"
date: "Wednesday, January 21, 2015"
output: html_document
---


```{r}
rm(list=ls())

library(raster)


#computer <- "~" #My computer
# computer <- "Z:/Amy" #Super computer
computer <- "//654cw-20990/Amy"

# directories
#   maxent.dir <- paste0(computer,"/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/")
# location of GH files
  GH.zonation.dir <- paste0(computer,"/GIS_data/Hunter/zonation/greater hunter/")

# location of LH files
  LH.coal.dir <- paste0(computer,"/GIS_data/Hunter/zonation/lower hunter coal paper/") 

# set projections
  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# import region mask for LHSA
 LH.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.mask.tif"))
  LH.mask[!is.na(LH.mask)] <- 0

# LHSA clipping mask
  LH.clipping.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.clipping.mask.tif"))
    LH.clipping.mask[!is.na(LH.clipping.mask)] <- 0

# LHSA urban clipping mask
  LH.urban.clipping.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.urban.clipping.mask.tif"))
    LH.urban.clipping.mask[!is.na(LH.urban.clipping.mask)] <- 0

# open species list
  protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))
    levels(protected.species$LH.sdm) <- c(NA,"SDM","SSI")

# import biodiversity feature names
  names <- as.vector(read.table(paste0(LH.coal.dir,'LHcoal_extant.spp'), header=F, sep='\t')[,6])
    names <- gsub("Z:/Amy/GIS_data/Hunter/zonation/lower hunter/extant/|_SDM.LH.tif","",names)

```

```{r clipping functions}
# function to clip to LHSA region
  clip.to.LH <- function(tiff, mask.raster){
    r <- raster(paste0(GH.zonation.dir,"extant_old/",tiff,"_SDM_GH.tif"),crs=GDA94.56)
    
    if( cellStats(r,max) > 1){
      r <- mask(crop(r,mask.raster),mask.raster,filename=paste0(LH.coal.dir,"species/extant/",tiff,"_SDM.LH.tif"),format="GTiff",overwrite=T)
      cat("Clipped",as.character(tiff),"to Lower Hunter","\n")}
      
  }

# function to clip to LHSA region
  clip.pre1750.to.LH <- function(tiff, mask.raster){
    r <- raster(paste0(GH.zonation.dir,"pre1750_old/",tiff,"_pre1750_SDM_GH.tif"),crs=GDA94.56)
      r <- mask(crop(r,mask.raster),mask.raster,filename=paste0(LH.coal.dir,"species/pre1750/",tiff,"_pre1750_SDM.LH.tif"),format="GTiff",overwrite=T)
      cat("Clipped",as.character(tiff),"to Lower Hunter","\n")
    }    

```

```{r clip rasters}

pb <- winProgressBar(title = "Clipping species rasters", label = "%",min = 0, max = length(names), initial = 0, width = 300)

for (i in seq(names)){
  
  species <- names[i]
  try({
    clip.to.LH(species,LH.clipping.mask)
    clip.pre1750.to.LH(species,LH.urban.clipping.mask)
    })
  setWinProgressBar(pb, i, sprintf("%d%% done", round(i)),round((i/length(names))*100,1))
}

close(pb)

```


```{r check for missing tifs}

computer <- "//654cw-20990/Amy"

# location of LH files
  LH.coal.dir <- paste0(computer,"/GIS_data/Hunter/zonation/lower hunter coal paper/species/") 


# import biodiversity feature names
  names <- as.vector(read.table(paste0(LH.coal.dir,'LHcoal_extant.spp'), header=F, sep='\t')[,6])
    names <- gsub("Z:/Amy/GIS_data/Hunter/zonation/lower hunter/extant/|_SDM.LH.tif","",names)

# check for missing sp
extant.tifs <- gsub("_SDM.LH.tif","",dir(paste0(LH.coal.dir,"extant/"), pattern="_SDM.LH.tif$"))
  missing.sp <- setdiff(names,extant.tifs)

```

```{r recut old tifs to replace missing tifs}
maxent.dir <- "//654cw-20990/Amy/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output"

# function to clip to LHSA region
  clip.to.LH <- function(tiff, mask.raster){
    r <- round(raster(paste0(maxent.dir,"/",taxa,"/pre1750/",tiff,"_avg.asc"),crs=GDA94.56)*1000,0)
    
    if( cellStats(r,max) > 1){
      r <- mask(crop(r,mask.raster),mask.raster,filename=paste0(LH.coal.dir,"extant/",tiff,"_SDM.LH.tif"),format="GTiff",overwrite=T,dataType='INT2U')
      cat("Clipped",as.character(tiff),"to Lower Hunter","\n")}
      
  }

# function to clip to LHSA region
  clip.pre1750.to.LH <- function(tiff, mask.raster){
    r <- round(raster(paste0(maxent.dir,"/",taxa,"/pre1750/",tiff,"_pre1750_avg.asc"),crs=GDA94.56)*1000,0)
      r <- mask(crop(r,mask.raster),mask.raster,filename=paste0(LH.coal.dir,"/pre1750/",tiff,"_pre1750_SDM.LH.tif"),format="GTiff",overwrite=T,dataType='INT2U')
      cat("Clipped pre1750 ",as.character(tiff),"to Lower Hunter","\n")
    }    



pb <- winProgressBar(title = "Clipping missing species rasters", label = "%",min = 0, max = length(missing.sp), initial = 0, width = 300)

for (i in seq(missing.sp)){
  
  species <- missing.sp[i]
  taxa <- protected.species$Taxa[protected.species$Scientific.Name==gsub("_"," ",missing.sp[i])]
  
  try({
    clip.to.LH(species,LH.clipping.mask)
    clip.pre1750.to.LH(species,LH.urban.clipping.mask)
    })
  setWinProgressBar(pb, i, sprintf("%d%% done", round(i)),round((i/length(missing.sp))*100,1))
}

close(pb)

```

```{r check for missing tifs}

computer <- "//654cw-20990/Amy"

# location of LH files
  LH.coal.dir <- paste0(computer,"/GIS_data/Hunter/zonation/lower hunter coal paper/") 


# import biodiversity feature names
  names <- as.vector(read.table(paste0(LH.coal.dir,'LHcoal_extant.spp'), header=F, sep='\t')[,6])
    names <- gsub("Z:/Amy/GIS_data/Hunter/zonation/lower hunter/extant/|_SDM.LH.tif","",names)

# check for missing sp
extant.tifs <- gsub("_SDM.LH.tif","",dir(paste0(LH.coal.dir,"species/extant/"), pattern="_SDM.LH.tif$"))
  missing.sp <- setdiff(names,extant.tifs)

```

```{r summarise LH coal taxa for paper}
computer <- "//654cw-20990/Amy"

# location of LH files
  LH.coal.dir <- paste0(computer,"/GIS_data/Hunter/zonation/lower hunter coal paper/") 


# import biodiversity feature names
  names <- as.vector(read.table(paste0(LH.coal.dir,'LHcoal_extant.spp'), header=F, sep='\t')[,6])
    names <- gsub("Z:/Amy/GIS_data/Hunter/zonation/lower hunter/extant/|_SDM.LH.tif","",names)
    names <- gsub("_"," ",names)

# open species list
  protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))

zonation.features <- data.frame(species=names, taxa=NA)

for(i in seq(names)){
  zonation.features$taxa[i] <- as.character(protected.species$Taxa[grepl(names[i],protected.species$Scientific.Name)])
  }


table(zonation.features$taxa)

```

