---
title: "Create veg communities rasters for coal paper"
author: "Amy Whitehead"
date: "Wednesday, January 21, 2015"
output: html_document
---


```{r}
rm(list=ls())
start.time <- proc.time()
computer <- "//654cw-20990/Amy"
computer <- "H:/UM backup"

  envi.directory <- paste0(computer,"/GIS_data/Hunter/vegetation/")
  output.directory <- paste0(computer,"/GIS_data/Hunter/zonation/lower hunter coal paper/vegetation communities/")

setwd(output.directory)

packages(raster)
packages(rgdal)
packages(maptools)

source("R Code/shp2raster.R")

LH.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.urban.clipping.mask.tif"))
  LH.mask[!is.na(LH.mask)] <- 0
LH.clipping.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/LH.clipping.mask.tif"))
  LH.clipping.mask[!is.na(LH.clipping.mask)] <- 0

GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")

 pre1750.shp <- readShapePoly(paste0(computer,"/GIS_data/Hunter/All data from harddrive/Pre1750V03/ArcView/lhcc_pre1750veg.shp"),proj4=CRS("+proj=utm +zone=56 +south +ellps=aust_SA +units=m +no_defs"),delete_null_obj=TRUE, force_ring=TRUE)
pre1750.shp <- spTransform(pre1750.shp,GDA94.56)
```

```{r test raster conversion}

pre1750.raster <- shp2raster(pre1750.shp,mask.raster = LH.mask,label="pre1750.raster",value=pre1750.shp$MAP_UNIT,bkg=0,save=F)

pct <- data.frame(MU_NAME=unique(pre1750.shp$MU_NAME),MAP_UNIT=NA)
  pct <- pct[!grepl("Water|Sand|Rocky Coast|Beach sands",pct$MU_NAME),]
  
  for(i in seq(pct$MU_NAME)){
    pct$MAP_UNIT[i] <- pre1750.shp$MAP_UNIT[pre1750.shp$MU_NAME == pct$MU_NAME[i]][1] 
  }


setwd("I:/Super Computer Data/GIS_data/Hunter/zonation/lower hunter coal paper/vegetation communities/")

pb <- winProgressBar(title = "Clipping community rasters", label = "%",min = 0, max = length(pct$MU_NAME), initial = 0, width = 300)

for(i in seq(pct$MU_NAME)){
  community <- pct$MU_NAME[i]
  r <- pre1750.raster
    r[r!=pct$MAP_UNIT[i]] <- NA
    r[r>=1] <- 1
  
  extant <- merge(mask(r,LH.clipping.mask),LH.clipping.mask)
  
  if(cellStats(extant,max)==1) {
    pre1750 <- merge(r,LH.mask)
    writeRaster(extant,paste0("extant/",gsub("\\/","",community),".tif"),overwrite=T)
    writeRaster(pre1750,paste0("pre1750/",gsub("\\/","",community),"_pre1750.tif"),overwrite=T)
    }
  rm(extant,pre1750)
  setWinProgressBar(pb, i, title = NULL, label = NULL)
  gc()
}

close(pb)

# check there is no overlap
extant.stack <- stack(dir("I:/Super Computer Data/GIS_data/Hunter/zonation/lower hunter coal paper/vegetation communities/extant/",pattern=".tif$",full.names=T))
  extant.sum <- sum(extant.stack)

pre1750.stack <- stack(dir("I:/Super Computer Data/GIS_data/Hunter/zonation/lower hunter coal paper/vegetation communities/pre1750/",pattern=".tif$",full.names=T))
  pre1750.sum <- sum(pre1750.stack)

```


The code below was the original approach but note that it leads to some overlap btwn communities, so don't use this code chuck. Just keeping it in case we need it for future reference.
```{r create community rasters}

pct <- unique(pre1750.shp$MU_NAME)
  pct <- pct[!grepl("Water|Sand|Rocky Coast|Beach sands",pct)]

setwd(output.directory)

pb <- winProgressBar(title = "Clipping community rasters", label = "%",min = 0, max = length(pct), initial = 0, width = 300)

for(i in seq(pct)){
  extant <- shp2raster(pre1750.shp[pre1750.shp$MU_NAME==pct[i],],mask.raster = LH.clipping.mask,label=paste0("extant/",gsub("\\/","",pct[i])),value=1,bkg=0)
  if(cellStats(extant,max)!=1) {
    file.remove(paste0("extant/",as.character(pct[i]),".tif"))
    } else {
      pre1750 <- shp2raster(pre1750.shp[pre1750.shp$MU_NAME==pct[i],],mask.raster = LH.mask,label=paste0("pre1750/",gsub("\\/","",pct[i]),"_pre1750"),value=1,bkg=0)
    }
  rm(extant,pre1750)
  setWinProgressBar(pb, i, title = NULL, label = NULL)
  gc()
}

close(pb)
```

