---
title: "Data for John Hunter"
author: "Amy Whitehead"
date: "Friday, October 17, 2014"
output: html_document
---

```{r setup}
rm(list=ls())

library(raster)
library(maptools)
library(rgdal)

#computer <- "~" #My computer
# computer <- "Z:/Amy" #Super computer
computer <- "//654cw-20990/Amy"

# set projections
  GDA94.56 <- CRS("+proj=utm +zone=56 +south +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs")
  GDA94 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

# import region mask for UHSA
 UH.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/UH_HCCREMS.mask.tif"))
  UH.mask[!is.na(UH.mask)] <- 0

# UHSA clipping mask
  UH.clipping.mask <- raster(paste0(computer,"/GIS_data/Hunter/mask files/UH_HCCREMS.clipping.mask.tif"))
    UH.clipping.mask[!is.na(UH.clipping.mask)] <- 0

UH.shp <- readShapePoly("~/GIS_data/Hunter/All data from harddrive/Upper Hunter Strategic Assessment Review/AoI/UHSA_StudyArea_within_HCCREMS.shp",proj4=GDA94)
    UH.shp <- spTransform(UH.shp,GDA94.56)

# open species list
  protected.species <- read.csv(paste0(computer,"/GIS_data/Hunter/species point data/IBRA threatened species list.csv"))
    plants <- protected.species$Scientific.Name[protected.species$Taxa=="plants"]

```

```{r functions}
rbind.match.columns <- function(input1, input2) {
    n.input1 <- ncol(input1)
    n.input2 <- ncol(input2)
 
    if (n.input2 < n.input1) {
        TF.names <- which(names(input2) %in% names(input1))
        column.names <- names(input2[, TF.names])
    } else {
        TF.names <- which(names(input1) %in% names(input2))
        column.names <- names(input1[, TF.names])
    }
 
    return(rbind(input1[, column.names], input2[, column.names]))
}

```

```{r extract & combine ssi data}
# ssi tec
ssi.tec <- read.csv(paste0(computer,"/GIS_data/Hunter/zonation/upper hunter/ssi.tec.csv"))
  ssi.tec <- ssi.tec[ssi.tec$in.UHSA == TRUE,"tec"]
 
all.tec <- d(tec=NA,easting=NA,northing=NA)

for(i in seq(ssi.tec)){
  sp.data <- read.table(paste0("//654cw-20990/Amy/GIS_data/Hunter/zonation/greater hunter/ssi_files/tecs/",ssi.tec[i]),sep="\t")
  sp.data$tec <- ssi.tec[i]
  colnames(sp.data) <- c("easting","northing","x","y","tec")
  all.tec <- rbind.match.columns(all.tec,sp.data)
}

all.tec$tec <- gsub("_GH.txt","",all.tec$tec)
all.tec$tec <- gsub("_"," ",all.tec$tec)
all.tec <- all.tec[complete.cases(all.tec),]
coordinates(all.tec) <- c("easting","northing")
proj4string(all.tec) <- GDA94.56

# clip to UHSA
all.tec <- all.tec[UH.shp,]

setwd("~/GIS_data/Hunter/species point data/For John Hunter/")
writeOGR(all.tec, ".", "Point EEC occurrences in UHSA", driver="ESRI Shapefile")
# writePointsShape(all.data,"~/GIS_data/Hunter/species point data/For John Hunter/Point flora occurrences in UHSA.shp")
```

```{r identify plants with poor models}
maxent.results <-read.csv(paste0(computer,"/GIS_data/Hunter/Maxent_files/ghm.pm/all_variables/output/plants/pre1750/maxentResults.csv")) 
  maxent.results <- maxent.results[grepl("average",maxent.results$Species),c("Species","Test.AUC")]
  maxent.results <- maxent.results[maxent.results$Test.AUC < 0.7,]
  maxent.results$Species <- gsub("//(average//)|//s","",maxent.results$Species)
  maxent.results$Species <- gsub("_"," ",maxent.results$Species)

UH.plants <- protected.species[!is.na(protected.species$upper.hunter) & protected.species$Taxa=="plants",c("Scientific.Name","greater.hunter","upper.hunter","UH.sdm")]

colnames(UH.plants) <- c("species","Total.records","UH.records","DataType")
UH.plants$DataType <- factor(UH.plants$DataType,levels=c("SDM","points"))
UH.plants$DataType[is.na(UH.plants$DataType)] <- "points"

write.csv(UH.plants, "List of plants with data in UHSA.csv",row.names=F)
```

```{r tecs}
tec.data <- read.csv("//654cw-20990/Amy/GIS_data/Hunter/Maxent_files/ghm.pm/species_data/brt.data_tecs.csv")

coordinates(tec.data) <- c("x","y")
proj4string(tec.data) <- GDA94.56

# clip to UHSA
tec.data <- tec.data[UH.shp,]
setwd("~/GIS_data/Hunter/species point data/For John Hunter/")
writeOGR(tec.data, ".", "Modelled EEC occurrences in UHSA", driver="ESRI Shapefile")


```